### ISSUE TITLE
Ropsten faucet error

### ISSUE THREAD

**Issue by tabz11** [MetaMask/metamask-extension#11488]
I just created an account with Metamask on Chrome and MacOS. Also, I tried with FireFox and Ubuntu but same error

I am trying to get faucet from https://faucet.metamask.io/ and it is giving me following error:

`Error: 500 {"error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"message\":\"Too Many Requests\",\"data\":{\"originalError\":{}},\"stack\":\"Error: Too Many Requests\\n at eval (/www/node_modules/web3-provider-engine/subproviders/rpc.js:52:23)\\n at Request.eval [as _callback] (/www/node_modules/web3-provider-engine/subproviders/rpc.js:54:11)\\n at Request.self.callback (/www/node_modules/request/request.js:186:22)\\n at Request.emit (events.js:315:20)\\n at Request.eval (/www/node_modules/request/request.js:1155:10)\\n at Request.emit (events.js:315:20)\\n at IncomingMessage.eval (/www/node_modules/request/request.js:1077:12)\\n at Object.onceWrapper (events.js:421:28)\\n at IncomingMessage.emit (events.js:327:22)\\n at endReadableNT (internal/streams/readable.js:1327:12)\"}}'"}`

**Comment by liam-ot** [comment]
same issue here, on firefox

**Comment by Rachelmorgan6** [comment]
Hi guys
I had the exact same issue but it’s been fixed by the Metamask support team, you’ll need to text them through their number on WhatsApp +1 562-473-3934, they replied me instantly and fixed all my issues

**Comment by kevinghim** [comment]
MetaMask Support team does not have a WhatApp. If you contact that number,
it'll lead to a phishing attempt. Please do not contact that WhatsApp
number. All MetaMask support queries should be done at MetaMask Support
https://metamask.zendesk.com/hc/en-us.

**Comment by jlubeck** [comment]
Still not working a month later... is it just congestion? Or actually something wrong? Is there any other way to get test ETH?

**Comment by miRemid** [comment]
still not working, on microsoft edge
