### ISSUE TITLE
Adding decimals apparently causes overflows

### ISSUE THREAD

**Issue by fnnhnsn** [MetaMask/metamask-extension#12718]
**Describe the bug**
If the user wants to send amounts that have decimals in it for custom token, e.g. 1.2 $PDEX/$PMON, MetaMask seems to cause an overflow and adjusts the value to 1.199999... . This seems to only happen with custom token and not ETH on Ethereum Mainnet or BNB on BSC Mainnet.
![image](https://user-images.githubusercontent.com/32572046/141956415-95dbf2fb-54ad-44af-971d-487acd4f19cd.png)

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to your Metamask extension.
2. Click on Send.
3. Select a custom token.
4. Enter a recipient address.
5. Add an amount with decimals.
6. See error

**Expected behavior**
Metamask just accepts the entered amount and does not update it on the fly.

**Comment by danjm** [comment]
I believe this is fixed in 10.6.0 due to https://github.com/MetaMask/metamask-extension/pull/12631

10.6.0 should begin roll out today or tomorrow

**Comment by barakshani** [comment]
@danjm I have 10.6.0 but it is not fixed. I also have 10.5.2 on a different machine, and this problem does not exist there.
Please consider re-opening this issue.
