### ISSUE TITLE
[Bug]: Error: Unable to determine contract standard in non-standard (MKR) token

### ISSUE THREAD

**Issue by brianmcmichael** [MetaMask/metamask-extension#14187]
### Describe the bug

User reported they couldn't send MKR token via Metamask. I've confirmed.

When trying to send MKR via the extension the UI halts with the loading icon and the consol prints `"Error: Unable to determine contract standard"`

MKR token is non-standard so some custom logic will likely need to be drawn up around it, the non-standard features are:

* `name` returns `bytes32` (instead of `string`)
* `symbol` returns `bytes32` (instead of `string`)
* `decimals` returns `uint256` (instead of `uint8`)

Note that these idiosyncrasies are not exclusive to MKR, and will be present in any [ds-token](https://github.com/dapphub/ds-token) derived token deployed prior to 2021.

### Steps to reproduce

1. Have MKR in wallet
2. Try to send MKR via metamask extension

### Error messages or log output

```shell
Uncaught (in promise) Error: Unable to determine contract standard
  at f.<anonymous> (common-1.js:7:379146)
  at Generator.throw (<anonymous>)
  at a (common-1.js:7:376936)
```
```


### Version

10.11.3

### Build type

_No response_

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

_No response_

**Comment by wajeshubham** [comment]
I am getting same error after trying to transfer my own ERC20 token through Ropsten Test Network.

**Comment by nathgilson** [comment]
Same with Goerli test net

**Comment by hdany** [comment]
I confirm I have the same problem.
[I openned a thread on Metamask community.](https://community.metamask.io/t/metamask-window-blank-spinner-and-error/19141)
This used to work perfectly on 10.11.3 (about a month ago), so it's a new introduced bug.
Looking forward for a fix

**Comment by kdumovic** [comment]
Happening to me too interacting with the DGD ERC20 contract

**Comment by PascalDuval** [comment]
Same problem

**Comment by chinu-dev** [comment]
We have method approve with same signature on vault contract, worked before and we need user to approve the spender contract first. Cannot workaround without downgrading metamask. 

Can it be written more defensively?

**Comment by gbalabasquer** [comment]
@kumavis sorry to tag you, but could someone look at this issue, please. It's impossible to interact with MKR at the moment using Metamask and it has been broken for some quite time.
Thanks.

**Comment by slayorktc** [comment]
Have this same issue on rinkeby trying to approve an erc20

**Comment by NinjaTurtle007** [comment]
I confirm this problem and here are more people having it with some more info 
https://community.metamask.io/t/i-cant-send-just-the-mkr-token/19753/15

**Comment by FrederikBolding** [comment]
Thanks for reporting everyone! Fix underway here: https://github.com/MetaMask/controllers/pull/830

**Comment by bschorchit** [comment]
Closing this as [the fix](https://github.com/MetaMask/controllers/pull/830) has been merged. This should be fixed in one of our next releases.

**Comment by Sofianel5** [comment]
I'm still having this issue with [the Ethernaut Dex challenge](https://ethernaut.openzeppelin.com/level/0xC084FC117324D7C628dBC41F17CAcAaF4765f49e)

**Comment by NinjaTurtle007** [comment]
me too, this has been closed with fix coming in next release 29 days ago, but still can't do anything with MKR token.

**Comment by NinjaTurtle007** [comment]
Any ETA on when we will be able to send our MKR tokens? :)

**Comment by MayasHaddad** [comment]
Still facing the issue on version `10.15.1`

**Comment by NinjaTurtle007** [comment]
Yes still can't interact with MKR tokens I confirm. 
Also feels like this issue has been abandoned, anyone?

**Comment by gbalabasquer** [comment]
> Update: the fix for this has been merged, but it depends on this other issue that have yet to be merged: #14906

Do you think it will be merged and release soon?
We are talking about Maker token, OG project, and old friend of Metamask. It has been broken for several months causing several issues to our users. Can this be escalated and fixed soon?

**Comment by bschorchit** [comment]
Update: this will fixed in extension release v10.19

**Comment by NinjaTurtle007** [comment]
> Update: this will be fixed in extension release v10.19

when will this be released?

**Comment by fepvenancio** [comment]
If you declare a variable:

uint8 public decimals;

And on the constructor set it to 0: 

decimals = 0; 

it will work as mentioned in the standards.

**Comment by kevinghim** [comment]
The fix will be released with 10.19.0 which will start rolling out late next week.

**Comment by JayWuzer** [comment]
Alright, when will this finally be rolled out? My MKR has been stuck in my MetaMask long enough and I am trying to exit tf out already lol

**Comment by Bultik41** [comment]
ср, 10 серп. 2022, 05:46 користувач JayWuzer ***@***.***>
пише:

**Comment by NinjaTurtle007** [comment]
> Alright, when will this finally be rolled out? My MKR has been stuck in my MetaMask long enough and I am trying to exit tf out already lol

I'm wondering the same thing.

**Comment by JayWuzer** [comment]
Hello...? I'd like to know when I can finally move my MKR out. It has been a really long time lol

**Comment by NinjaTurtle007** [comment]
yes we were told it should be a week ago......

**Comment by JayWuzer** [comment]
Bruh.

**Comment by JayWuzer** [comment]
I'm pissed lol

**Comment by JayWuzer** [comment]
Bruh it has been damn near two weeks since I first came here to drop a comment. What're y'all doing lol

**Comment by JayWuzer** [comment]
HELLO???

**Comment by FrederikBolding** [comment]
The release of `10.19.0` has been delayed a bit. It'll likely be released early September.

**Comment by liszechung** [comment]
really cant imagine this small bug couldnt be fixed and merged for a few months.
that's bad

**Comment by rafinskipg** [comment]
you can transfer your MKR from the contract using the transferFrom method @JayWuzer

**Comment by JayWuzer** [comment]
> rafinskipg

Wtf is the "transferFrom" method?

**Comment by JayWuzer** [comment]
Boiii if y'all think you can just silience your way outta this, you're trippin'.

I WANT MY FUNDS NOW!!!

**Comment by LordJayWu** [comment]
Hello???

**Comment by FrederikBolding** [comment]
@LordJayWu This should be fixed in the latest version of the extension. Are you still having the issue?

cc @bschorchit

**Comment by LordJayWu** [comment]
Finally! Thank you, it worked. 👍

**Comment by bschorchit** [comment]
Closing as this has now been fixed! If you are still having problems, please update your MetaMask to the latest version. If you find any other issue after updating it, let us know!
Thank you for all your reports and help!

**Comment by csokun** [comment]
Hi, I'm encountered the same issue metamask version: `10.21.2` contract details https://etherscan.io/address/0x3a859b9ea4998d344547283c7ce8ebc4abb77656

**Comment by sonnh58** [comment]
Hi, same issue when decimal 0 in `10.21.2`

**Comment by obaviet** [comment]
I still have problem with VNDC

**Comment by parit90** [comment]
Try not to set decimal value as 0 in constructor of the smart-contract

**Comment by curthose** [comment]
Hello, same issue when decimal 0 in 10.22.2.

**Comment by bschorchit** [comment]
The issue with decimal 0 is fixed in version 10.23.0 which will start rolling out to users within the next week. 
More info here: https://github.com/MetaMask/metamask-extension/issues/16596
