### ISSUE TITLE
[Bug]: setApprovalForAll Displays Operator Address, Not Target Contact Address

### ISSUE THREAD

**Issue by adraffy** [MetaMask/metamask-extension#15251]
### Describe the bug

let `A` = my address
let `B` = contract
let `C` = another address

Call `B.setApprovalForAll(C, true)`

Expect: Metamask `A -> B` calling `setApprovalForAll(C, true)`

Instead, interface shows `A -> C` calling `setApprovalForAll(C, true)`

![image](https://user-images.githubusercontent.com/225900/179166363-c0a0045c-d88f-4006-8fd6-3ea459ef6966.png)

### Steps to reproduce

1.  Call `setApprovalForAll`

### Version

10.14.7

### Browser

Firefox

### Operating system

Windows

**Comment by bschorchit** [comment]
I think this is addressed already on v10.18 @seaona

**Comment by seaona** [comment]
ohh that seems the case @bschorchit

**Comment by seaona** [comment]
I see what you mean @adraffy , that is indeed a bug but it is mitigated on v10.18.0, as `setApprovalForAll` screen is re-worked and data is parsed in a more digestible manner. You still won't see the contract address, but it is indicated clearly to which address are you giving permissions to. It will look like this:

![image](https://user-images.githubusercontent.com/54408225/179502343-33d13a38-7e96-4e5e-86b0-78ef49e10e27.png)

**Comment by jqphu** [comment]
It would be great to be still be able to see the contract address somewhere.

For example, if a NFT contract has the same symbol name as another contract there will be a collision and we won't be able to know which contract we're interacting with.

Potentially a line below `Granted to:` that says `Interacting with:`?

**Comment by bschorchit** [comment]
Hey @jqphu, if you click on the NFT name in the headers you are either directed to etherscan or will be able to copy the contract address. We have this ticket https://github.com/MetaMask/metamask-extension/issues/15697 also in progress that will also make this info more discoverable. 
Closing this issue as the first fix has already been merged and released.

**Comment by adraffy** [comment]
The current version of this dialog is **absolutely horrendous**.

The most critical pieces of information are not visible to the user — **why?**

1. WHAT contract is being called — `B` in my original example
2. WHAT address is getting approval — `C` in my original example

![image](https://github.com/MetaMask/metamask-extension/assets/225900/b9a92bd5-3454-44bd-8ec3-92ab7c4fc5a7)
