### ISSUE TITLE
[Bug]: Unable to send token, MetaMask hangs – "Uncaught (in promise) Error: Unable to determine contract standard"

### ISSUE THREAD

**Issue by deshvin** [MetaMask/metamask-extension#16596]
### Describe the bug

Trying to send UBX token (0xF5B5eFc906513b4344EbAbCF47A04901f99F09f3), after pressing the Send button MetaMask hangs with a loading icon.

### Steps to reproduce

1. Select UBX token from asset list
2. Select Send
3. Error occurs

### Error messages or log output

```shell
Uncaught (in promise) Error: Unable to determine contract standard
  at h.<anonymous> (common-0.js:1:260805)
  at Generator.throw (<anonymous>)
  at s (common-0.js:1:257835)
```

### Version

10.22.1, 10.22.2

### Browser

Chrome, Brave

### Operating system

MacOS

**Comment by deshvin** [comment]
Seems like this may be affecting all tokens with 0 decimals.

**Comment by Nanimustshine** [comment]
> ### Describe the bug
> 
> Trying to send UBX token (0xF5B5eFc906513b4344EbAbCF47A04901f99F09f3), after pressing the Send button MetaMask hangs with a loading icon.
> 
> ### Steps to reproduce
> 
> 1. Select UBX token from asset list
> 2. Select Send
> 3. Error occurs
> 
> ### Error messages or log output
> 
> ```shell
> Uncaught (in promise) Error: Unable to determine contract standard
>   at h.<anonymous> (common-0.js:1:260805)
>   at Generator.throw (<anonymous>)
>   at s (common-0.js:1:257835)
> ```
> 
> 
> ### Version
> 
> 10.22.1, 10.22.2
> 
> ### Build type
> 
> _No response_
> 
> ### Browser
> 
> Chrome, Brave
> 
> ### Operating system
> 
> MacOS
> 
> ### Hardware wallet
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by bschorchit** [comment]
> Seems like this may be affecting all tokens with 0 decimals.

Does it only affects tokens with 0 decimals, @deshvin ?

**Comment by deshvin** [comment]
@bschorchit 
Yes it seems to only affect tokens with 0 decimals as far as I can tell. Have seen multiple reports in ZD tickets, all tokens have 0 decimals.

**Comment by nikola43** [comment]
I got the same error with a token with 0 decimals
https://sepolia.etherscan.io/address/0x092f480C2c6f8e3809712111904D9E4c19543AaA#code

Version
10.22.2

Build type
No response

Browser
Chrome, Firefox

Operating system
Ubuntu 22.10

Hardware wallet
No response

Additional context
No response

**Comment by seaona** [comment]
Thank you for reporting this issue! It will be fixed on our next release `10.23.0`

**Comment by PeterYinusa** [comment]
Fixed in [10.23.O](https://github.com/MetaMask/metamask-extension/pull/16485) [Unreleased]

**Comment by ralphsmith80** [comment]
I'm still getting this error with USDC and USDT. Both have 6 decimals. 

Version:
10.23.2

Browser edge:
Microsoft Edge
Version 108.0.1462.76 (Official build) (64-bit)


![image](https://user-images.githubusercontent.com/1655592/211432205-d54cede3-1355-4b9f-81d2-6567159c763e.png)

**Comment by deshvin** [comment]
@ralphsmith80

I tested on my end and had the same issue sending any ERC20, only ETH worked.

Resolved it by going to **Settings** > **Advanced** > **IPFS Gateway**, and changing it to https://ipfs.io/ipfs (it was originally dweb.link).

After changing this, sending ERC20s worked again. I changed it back to dweb.link to see what would happen and it continued to work.

**Comment by eric248550** [comment]
@deshvin it works for me!
why did this happen? the contract address has nothing to do with ipfs
And this error occurs on common erc20 token

**Comment by deshvin** [comment]
@eric248550 
I've no clue why changing the IPFS setting works, nor do I remember why exactly I tested changing that specific setting during troubleshooting. But hey, it works!

**Comment by Mentors4EDU** [comment]
Maybe consider reopening because of zero decimal support problems
