### ISSUE TITLE
token balance is not loaded anymore after... 

### ISSUE THREAD

**Issue by ycmath** [MetaMask/metamask-extension#1917]
I participated in ZRX crowdsale (Contract Address: 0xd4fd252d7d2c9479a8d616f510eac6243b5dddf9 )  
and new ZRX balance popped up in token tab....
then there comes "There was a problem loading your token balances" msg instead token balance list.

and at my etherscan address I can still find my ERC20 token balances though.

**Comment by flyswatter** [comment]
Sorry, so many people are checking their ZRX token balances at once, that our token list is having trouble loading. This should be fixed soon.

**Comment by flyswatter** [comment]
Sorry, our token list is a little brittle right now, and our backend is a bit overloaded with people trying to add their new 0x tokens.

Try [connecting to a local node](https://support.metamask.io/kb/article/2-using-a-local-node), or just waiting a few hours until this traffic has relieved a bit.

**Comment by kumavis** [comment]
This was resolved in fix published today

**Comment by uworld66** [comment]
I hate to burst your bubble but this issue is not fixed and remains.

**Comment by leafcutterant** [comment]
#3243 is a duplicate, but I'd recommend centering the issue there.

And yes, the issue remains.
