### ISSUE TITLE
[Bug]: Showstopper completely unusable Metamask infinite load

### ISSUE THREAD

**Issue by daweth** [MetaMask/metamask-extension#21598]
### Describe the bug

No networks will connect. Infintie spin.

Rabby works fine.

### Expected behavior

The wallet should open..

### Screenshots/Recordings

<img width="353" alt="Screen Shot 2023-10-28 at 5 18 50 PM" src="https://github.com/MetaMask/metamask-extension/assets/46637826/881a351a-fa77-4fe0-978e-b676fae02dd5">

### Steps to reproduce

Simply opening the extension

### Version

.

### Build type

None

### Browser

Brave

### Operating system

MacOS

### Additional context

Metamask is a complete joke of a product.

The only thing your company is good at doing is raising money.

Cannot deliver a usable product.

**Comment by xh3b4sd** [comment]
@daweth I had the same problem. Do you have "Site access" maybe set to "On click"? This was the case for me. I changed the setting and then noticed that the extension loaded again when using "On all sites". 

<img width="681" alt="Screenshot 2023-11-02 at 18 12 32" src="https://github.com/MetaMask/metamask-extension/assets/552769/2f70dd73-b1c8-41dc-b3bb-81797b7f8907">

**Comment by danjm** [comment]
@daweth Can you give more information about when you started seeing this problem, and what metamask version you were using? And if you install in a different browser, do you see the same problem?

**Comment by FicoMuse** [comment]
i have the same issue for the last few days
i have MM v 11.4.0
also my RPC is POKT network to Ethereum

**Comment by doctorrobinson** [comment]
Hey @FicoMuse and @daweth , POKT's updated their endpoints for free public RPC. 

Why & How:
https://www.pokt.network/deprecation-of-rpc-endpoints-what-you-need-to-know/

If this doesn't solve your issue, can you @ me please? I've heard from one person they had to reinstall metamask, but that seems to be an edge case so far.

**Comment by FicoMuse** [comment]
Thanks @doctorrobinson how exactly do i do the: Delete the loading overlay using the inspector tool. 
A bit of a noob in this area. Thanks!

**Comment by adrienne-adz** [comment]
@FicoMuse - would you be willing to come into the POKT Network Discord and we'll help you get it sorted?

https://discord.gg/r4Qz6UQ8

**Comment by daweth** [comment]
seems to be fixed now, though this was a months-long issue for me before I made this issue @doctorrobinson

**Comment by doctorrobinson** [comment]
> seems to be fixed now, though this was a months-long issue for me before I made this issue @doctorrobinson

Well it's partially reassuring to know it's not just from RPC changes, but frustrating that there's been no metamask support on this issue. We'll keep investigating as people are reporting these problems.

**Comment by tdev00** [comment]
My issue remains unresolved. I submitted a bug report, but it was closed as a duplicate. Here is my ticket: [MetaMask GitHub Issue #21719](https://github.com/MetaMask/metamask-extension/issues/21719).

The urgency of this ticket should be escalated to high since it renders MetaMask inoperative. While reinstalling the extension could potentially resolve the problem, this isn't a viable option for users managing multiple addresses. I suspect the root of the problem may be the deprecation of the POKT RPC endpoint. A possible solution could involve swapping the RPC endpoint on the server side, or alternatively, the MetaMask team could contact the POKT team to discuss a temporary rollback of their changes.

I have tried the below, but none of them work:
- Cleared the browser cache and cookies.
- Closed the browser completely and restarted the PC.
- Disabled the VPN.
- Tried to remove the loading overlay via CSS to access the settings.
- Ensured the extension's access is set to "On all sites."
- Attempted to open the extension in incognito mode.
- Updated Chrome. Current version: 119.0.6045.106 (Official Build) (64-bit)

**_Please note that this issue does not exist on Brave browser_**

**Comment by danjm** [comment]
thanks @tdev00, we are currently working towards fixing this.

You said that this does not exist on Brave browser. Did you have the POKT network added to your MetaMask install on the Brave browser?

**Comment by tdev00** [comment]
> thanks @tdev00, we are currently working towards fixing this.
> 
> You said that this does not exist on Brave browser. Did you have the POKT network added to your MetaMask install on the Brave browser?

@danjm The POKT network is not added to my MM on the Brave browser.
Thank you!

**Comment by danjm** [comment]
@tdev00 Could you check if there are errors in the background console and then share a screen shot or a copy paste here?

Attached is a video of how to see errors in the background console:


https://github.com/MetaMask/metamask-extension/assets/7499938/d0efd6d1-f905-424f-88bf-941ded3f3cb2

**Comment by tdev00** [comment]
> @tdev00 Could you check if there are errors in the background console and then share a screen shot or a copy paste here?
> 
> Attached is a video of how to see errors in the background console:
> Peek.2023-11-09.10-54.mp4
> 
> To summarize the steps:
> 
>     1. Open chrome
> 
>     2. Go to chrome://extensions
> 
>     3. Toggle on "Developer mode"
> 
>     4. Toggle metamask off and of
> 
>     5. Click "background.html" under metamask
> 
>     6. Click the console tab in the window that opens
> 
>     7. Screenshot or copy+paste the errors that you see

Here you go @danjm :
![image](https://github.com/MetaMask/metamask-extension/assets/63981572/09d3d591-1040-4d6a-a2d8-7f3e86580c45)

**Comment by tdev00** [comment]
@danjm just for your information, there are plenty of other people who're also experiencing similar issues. 

Here is the Reddit post: 
https://www.reddit.com/r/Metamask/s/kJWRbDOWu9

**Comment by Curerer** [comment]
BIDV.Mastercard.5174530025331104

**Comment by tdev00** [comment]
@danjm Where are we on this issue? What is the ETA for resolving this? Thanks.

**Comment by harleauxcarrera** [comment]
Experiencing the same/similar issue on Chrome but I have no access to anything in the dashboard even if deleting elements inside the inspector tool.

Like @tdev00 ,I  too have tried the following:

Cleared the browser cache and cookies.
Closed the browser completely and restarted the PC.
Tried to remove the loading overlay via CSS to access the settings.
Ensured the extension's access is set to "On all sites."
Attempted to open the extension in incognito mode.

<img width="1493" alt="Screenshot 2023-11-16 at 12 31 40 PM" src="https://github.com/MetaMask/metamask-extension/assets/14799265/f5e448d1-15ff-4627-a4d1-326a7db54034">


@danjm Support Ticket here: https://support.metamask.io/hc/en-us/requests/1095762?page=1

@doctorrobinson any insights on this one?

**Comment by tdev00** [comment]
@harleauxcarrera try to update your Metamask to version **11.5.0** as it is a new release. Then, clear your cache and cookies.

**Comment by tdev00** [comment]
@danjm @kevinghim I realize that version 11.5.0 has been released. **_The issue still persists._** 

Here are the steps I've taken:

1.     Cleared the browser cache and cookies.
2.     Closed the browser completely and restarted the PC.
3.     Disabled the VPN.
4.     Tried to remove the loading overlay via CSS to access the settings.
5.     Ensured the extension's access is set to "On all sites."
6.     Attempted to open the extension in incognito mode.
7.     Updated Chrome. Current version: 119.0.6045.159 (Official Build) (64-bit)

None of the above steps work. Should I create a new bug ticket?

![image](https://github.com/MetaMask/metamask-extension/assets/63981572/4c37aeff-4bc9-4d6e-9bd3-1c19e699dcc0)

![image](https://github.com/MetaMask/metamask-extension/assets/63981572/67c4f7cb-db4d-4bd9-ae8f-a78a636e5410)

**Comment by danjm** [comment]
This was fixed in https://github.com/MetaMask/metamask-extension/pull/21854, which will be in v11.5.1

v11.5.1 was submitted to chrome yesterday, so hopefully it will be available to users some time today. I will comment here again once it is available to users

**Comment by harleauxcarrera** [comment]
> @harleauxcarrera try to update your Metamask to version **11.5.0** as it is a new release. Then, clear your cache and cookies.

Thanks @tdev00 although I tried this and the issue still persists.

**Comment by tdev00** [comment]
@harleauxcarrera version 11.5.1 will be released either today or tomorrow. They say that build will fix the issue.

**Comment by carynx** [comment]
> @harleauxcarrera version 11.5.1 will be released either today or tomorrow. They say that build will fix the issue.

did it fix the issue yet ?

**Comment by curiousronin** [comment]
Issue is still not resolved. I noticed my Metamask version on Brave is still 11.4.1. Not sure how to update when I can't even open Metamask with this issue?

**Comment by tdev00** [comment]
@danjm THANK GOD! It is finally fixed on version 11.5.1. Awesome work devs.

**Comment by harleauxcarrera** [comment]
Issue fixed on my end after update @carynx. 
thanks @danjm

**Comment by daweth** [comment]
<img width="340" alt="Screen Shot 2023-11-23 at 6 00 20 AM" src="https://github.com/MetaMask/metamask-extension/assets/46637826/d7b3bd2c-6758-49ff-a7d3-8a1fe98afc2b">
issue still here on certain networks?

**Comment by benjisclowder** [comment]
**Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
 
 We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
 
1. What PR fixed the issue?
2. Can you pinpoint the commit from which the issue originated?
3. Write a short explanation of the technical cause of the bug
4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?

Please provide your answers as a reply to this comment and tag me as well.

You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!

Tagging eng. who added the fix: @danjm

**Comment by benjisclowder** [comment]
> **Collaborative Effort Required for Root Cause Analysis (RCA) on Critical Issues**
> 
> We are quickly approaching the end of the quarter and we encourage you once again to take some moments and perform RCA on this critical issue. You may do so by answering the questions below:
> 
> 1. What PR fixed the issue?
> 2. Can you pinpoint the commit from which the issue originated?
> 3. Write a short explanation of the technical cause of the bug
> 4. How could we have avoided merging this bug? What would have had to be different about our code, tests or processes?
>    4.1. Were there any missing unit, e2e or manual tests that could have preempted this issue?
>    4.2. Were there any other elements lacking, such as typed code, comprehensive documentation, well-architected APIs, etc., that might have prevented this issue?
>    4.3. If your answer to a and b is no, then is there anything at all that you can think of that, if it had been different before this bug was introduced, would have prevented it from being merged?
> 
> Please provide your answers as a reply to this comment and tag me as well.
> 
> You can read more about the initiative [here](https://www.notion.so/metamask-consensys/MetaMask-Quality-Initiatives-9e76f1faabda4683830d7a770a0a0b59?p=a80fc81e06d646f389f11e4c171e2ffe&pm=s). Thank you!
> 
> Tagging eng. who added the fix: [@danjm](https://github.com/danjm)

Hi, @danjm  , if you're not able to conduct RCA on this issue, is there anyone you can assign this to? I would very much appreciate it. Thank you!

**Comment by daweth** [comment]
this issue should be re opened. I am having the same problem again

@benjisclowder @danjm @metamaskbot 
<img width="327" alt="Screen Shot 2024-08-14 at 12 31 59 PM" src="https://github.com/user-attachments/assets/91542af5-f060-42e7-bbf2-c54fd14f798d">
