### ISSUE TITLE
Ui fails to start - Blank Screen

### ISSUE THREAD

**Issue by CannonFireAtWill** [MetaMask/metamask-extension#2217]
I keep getting a blank screen when I open up MetaMask. I disabled the plugin, reinstalled the plugin, restarted my browser, and restarted my computer. Still nothing works.

Here's the error log message from the background inspection:

**_Uncaught SyntaxError: Unexpected identifier  background.js:50300_** 

![image](https://user-images.githubusercontent.com/32383411/31004203-3aa524fc-a4a8-11e7-8727-325b84f72ba1.png)

**Comment by CannonFireAtWill** [comment]
Here are the popup logs:
Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
 popup.js:55492 

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs popup.js:73177

**Comment by danfinlay** [comment]
1. Try restarting the browser
2. Try looking at [background logs](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome).

**Comment by CannonFireAtWill** [comment]
`Uncaught SyntaxError: Unexpected identifier background.js:50300 `
![image](https://user-images.githubusercontent.com/32383411/31039119-da2e30c2-a52f-11e7-825d-585aae428fca.png)

**Comment by CannonFireAtWill** [comment]
It's been like this all day! I'm using windows vista.
![image](https://user-images.githubusercontent.com/32383411/31039188-7d42901e-a530-11e7-8f15-451a64b9f8f9.png)

**Comment by danfinlay** [comment]
If you click the line number to the right of that "Unexpected Identifier" log, it'll show you the line that is causing the error.

If you have your seed phrase backed up, you might get around this whole debacle by uninstalling & reinstalling MetaMask.

**Comment by CannonFireAtWill** [comment]
I tried uninstalling and reinstalling it. When I open it up after reinstalling, I get the blank screen with no option to do anything, restoring by seed included.

Here's the code I found on that line:

`async initialize () {}`

**Comment by danfinlay** [comment]
That doesn't make any sense. Our initialize function has code in it that sets up the application, it kindof seems like you found a bug in chrome's extension distribution.  What version of MetaMask does it say in the "Manage Extensions" section?

**Comment by danfinlay** [comment]
One last one, before I break for the day:

You could download a release directly off our github page, and load it up directly from the Manage Extensions section. You won't get auto-updates, though:

https://github.com/MetaMask/metamask-extension/releases

**Comment by CannonFireAtWill** [comment]
3.10.6.

I was able to restore from seed with the firefox version but got this error when I tried to load up my tokens:
![image](https://user-images.githubusercontent.com/32383411/31039803-a4abe9a2-a535-11e7-9cba-866071dcd0ad.png)

**Comment by CannonFireAtWill** [comment]
I used my windows 10 system with no problems.

**Comment by danfinlay** [comment]
Yeah, the token list isn't working on Firefox yet, they have some special restrictions on web requests.

**Comment by PearSlice** [comment]
I had the exact same issue at the line
`async initialize () {}`

I was using chromium version 53-something on Ubuntu 14.04.

Updating chromium to the latest version solved it.

**Comment by Zanibas** [comment]
Will check on Windows 10 to see if this issue is still relevant.

**Comment by kumavis** [comment]
@CannonFireAtWill this should be resolved if you update to latest chrome. let us know if updating does not work for you

**Comment by lopezi** [comment]
updating did not solve it for me, can this be some incompatibility when you have chrome open in 2 different machines?

**Comment by lopezi** [comment]
Pop up log:

Refused to connect to 'about:blank' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com".

**Comment by lopezi** [comment]
_"can this be some incompatibility when you have chrome open in 2 different machine"_ because right here it works in one machine but not in the other

**Comment by tmashuang** [comment]
Was the previous comment a screenshot? It seems there was an issue trying to post the screenshot of the popup log. Seems that there is an issue with persisting state with a Chrome instance. If one machine works fine and they both have the same associated accounts, use this guide to ensure you have your seed phrase backed up. [Always be backed up]( https://support.metamask.io/kb/article/28-abbu-always-be-backed-up-how-to-make-sure-your-12-word-metamask-seed-phrase-is-backed-up). Afterwards, a fresh install and importing your vault/den/accounts could solve the issue.

**Comment by danfinlay** [comment]
> "can this be some incompatibility when you have chrome open in 2 different machines" because right here it works in one machine but not in the one where i'm developing bc

This is an interesting question, I recently had a cryptographer suggest that maybe our seed phrase issue is related to some operating systems using different character encodings for the same seed phrase.

If you can verify two different operating systems that restore the same seed phrase differently, that would be a huge find, and I think would make you eligible for our open related bug bounties. https://github.com/MetaMask/metamask-extension/issues/2577

**Comment by cwynd** [comment]
Hi, I'm getting this problem in Chrome 48.0.2564.109 (64-bit). The background logs show:
```
Uncaught SyntaxError: Unexpected token =
background.js:35969
```
35969 is:
```
35969: function generateSalt (byteCount = 32) {
  var view = new Uint8Array(byteCount)
  global.crypto.getRandomValues(view)
  var b64encoded = btoa(String.fromCharCode.apply(null, view))
  return b64encoded
}
```
OS: Debian Jessie / XFCE

Would really appreciate any suggestions / advice. Thanks!

PS: googling for "Uncaught SyntaxError: Unexpected token =" is loads of fun..

**Comment by lopezi** [comment]
It's a bit boring but reinstalling metamask usually fixes it.

**Comment by cwynd** [comment]
Thanks so much for the suggestion. In fact I have fixed it now. I thought my version of chrome was current, but it wasn't - updating to latest resolved the problem. Thanks again!

**Comment by Cole128** [comment]
I am getting the same on Firefox 59.0.2.
