### ISSUE TITLE
[Bug]: Completely unusable Metamask infinite load

### ISSUE THREAD

**Issue by jeffbzs** [MetaMask/metamask-extension#22533]
### Describe the bug

Nothing happens, just a download with no inscriptions

### Expected behavior

The wallet should open..

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/156550760/440a84d2-8b28-4ca6-9085-ed0e042a8866)

### Steps to reproduce

Simply opening the extension

### Version

11.7.2

### Build type

None

### Browser

Firefox

### Operating system

Windows

**Comment by nostitos** [comment]
https://github.com/MetaMask/metamask-extension/issues/22462

This looks urgent to me

**Comment by jeffbzs** [comment]
@danjm

**Comment by jeffbzs** [comment]
@tdev00 @harleauxcarrera

**Comment by jeffbzs** [comment]
@kevinghim

**Comment by danjm** [comment]
@nostitos What browser version are/were you using when you saw this problem?

**Comment by danjm** [comment]
@jeffbzs Thank-you. Can you now click the arrows next to `SES_UNHANDLED_REJECTION` and `Error#1` and `Error#2`, and share what is shown after those are opened?

**Comment by jeffbzs** [comment]
> @jeffbzs Thank-you. Can you now click the arrows next to `SES_UNHANDLED_REJECTION` and `Error#1` and `Error#2`, and share what is shown after those are opened?

![image](https://github.com/MetaMask/metamask-extension/assets/156550760/54bf544e-4e1b-4d8f-a311-8a99c8b1ff1d)

**Comment by danjm** [comment]
Thanks. And can you tell me when did you last see MetaMask working? And did anything change about your browser or MetaMask setup between when it was last working and when you first saw this problem?

**Comment by jeffbzs** [comment]
> Thanks. And can you tell me when did you last see MetaMask working? And did anything change about your browser or MetaMask setup between when it was last working and when you first saw this problem?

The last time Metamask was working was 2 days ago, nothing has changed in my browser, I haven't done anything.

**Comment by danjm** [comment]
Do you know if the MetaMask version updated during that time? This is unlikely, as we have not published a new version to firefox in over 3 weeks, but I'm checking in case you ever manually update.

**Comment by jeffbzs** [comment]
> Do you know if the MetaMask version updated during that time? This is unlikely, as we have not published a new version to firefox in over 3 weeks, but I'm checking in case you ever manually update.

No, Metamask has not been updated in that timeframe

**Comment by jeffbzs** [comment]
> @jeffbzs what version of firefox are you using?

121.0.1 (64-bit)

**Comment by jeffbzs** [comment]
> @jeffbzs what version of firefox are you using?

Do you think it’s possible to find a solution for this problem?

**Comment by nelwincatalogo** [comment]
Same issue, infinite loading upon opening metamask extension

**Chrome Dev Version:** 
Version 122.0.6238.2 (Official Build) dev (64-bit)

**Metamask Version:**
11.7.3

**Console Errors:**
![image](https://github.com/MetaMask/metamask-extension/assets/45314780/7837451e-06ef-4d1d-97d0-d65e7943f290)

**Comment by nelwincatalogo** [comment]
Tried uninstalling the extension and installing again, same issue

**Comment by danjm** [comment]
@jeffbzs I believe we will be able to solve your problem, but it is unclear how long it will take. I will be trying to reproduce your problem on firefox 121 today

**Comment by gitmaxton** [comment]
Same problem in Google Chrome. Appeared on January 13, 2024. During this time I reinstalled the extension, it did not help. Today the browser was updated also did not solve the problem.
As far as I remember, the bug appeared after the extension froze and the browser was forced to restart.

**Chrome Dev Version:**
122.0.6251.0 (Official build), canary (64 bit)

**Metamask Version:**
11.7.3

Console Errors:
![bagii](https://github.com/MetaMask/metamask-extension/assets/156803155/5f1539e3-3831-4667-8ed2-c3756e641c6f)

**Comment by danjm** [comment]
@gitmaxton did you see my above comment?

> The problem you are seeing is unique to chrome versions 122 and later. If you install the stable or beta chrome build (v120 or v121), MetaMask should work fine. We are currently working on solving the problem introduced with chrome 122

If you install chrome stable or beta, you should be able to get MetaMask to work

**Comment by jeffbzs** [comment]
> @gitmaxton did you see my above comment?
> 
> > The problem you are seeing is unique to chrome versions 122 and later. If you install the stable or beta chrome build (v120 or v121), MetaMask should work fine. We are currently working on solving the problem introduced with chrome 122
> 
> If you install chrome stable or beta, you should be able to get MetaMask to work

hi @, is there any news?

**Comment by gauthierpetetin** [comment]
Issue potentially related: https://github.com/MetaMask/metamask-extension/issues/22589

**Comment by jeffbzs** [comment]
Hi @danjm, if possible, please give us some updates, we are all worried, cause our money are being stuck..

**Comment by danjm** [comment]
@jeffbzs We are still investigating. This is not happening to many users and we cannot reproduce it, so it will take time to find the cause of the problem. Can you check whether the same errors as shown here https://github.com/MetaMask/metamask-extension/issues/22589 (about "IndexDB") are showing up in your console?

Also, it may make sense for you to uninstall and reinstall, or install metamask in a different browser. But only do that if you have your secret recovery phrase, or individually imported private keys, backed up. Do you have those backed up?

**Comment by nostitos** [comment]
To reproduce?
Try running metamask on Chrome Canary.

It does the same thing on multiple devices.

**Comment by jeffbzs** [comment]
> @jeffbzs We are still investigating. This is not happening to many users and we cannot reproduce it, so it will take time to find the cause of the problem. Can you check whether the same errors as shown here #22589 (about "IndexDB") are showing up in your console?
> 
> Also, it may make sense for you to uninstall and reinstall, or install metamask in a different browser. But only do that if you have your secret recovery phrase, or individually imported private keys, backed up. Do you have those backed up?

I don't have a backup of the imported private keys

I don't understand which one you are talking about (about "IndexDB")

**Comment by Gudahtt** [comment]
Thanks @nostitos ! To clarify, we are able to reproduce on Chrome Canary, and a fix is on the way. We are sorry for the inconvenience, and advise that you use Chrome stable or beta in the meantime. If you have not backed up your secret recovery phrase and help extracting it from your Chrome Canary install, please contact our support team and ask for help (click "Resources" => "Support" on our website, [metamask.io](https://metamask.io))

**Comment by mikeinweb** [comment]
> Thanks @nostitos ! To clarify, we are able to reproduce on Chrome Canary, and a fix is on the way. We are sorry for the inconvenience, and advise that you use Chrome stable or beta in the meantime. If you have not backed up your secret recovery phrase and need help recovering it from your Chrome Canary install, please contact our support team and ask for help (click "Resources" => "Support" on our website, [metamask.io](https://metamask.io))
> 
> We have been unable to reproduce the issue on Firefox so far.

Chrome Beta was just updated to Version 122.0.6261.6 (Official Build) beta (64-bit) and MetaMask 11.7.4 has infinite loading problem. Please ship fix ASAP.

**Comment by nostitos** [comment]
Seems like you should also test on canary to catch problems early since
whatever problem there is likely to end up in main branch.

**Comment by danjm** [comment]
The v11.7.5 release fixes this. It has been submitted to chrome and we will roll it out as soon as possible.

I agree that we need to include Chrome Canary and Chrome Beta in our testing, and we will be improving our processes to do this.

**Comment by nostitos** [comment]
> The v11.7.5 release fixes this. It has been submitted to chrome and we will roll it out as soon as possible.
> 
> I agree that we need to include Chrome Canary and Chrome Beta in our testing, and we will be improving our processes to do this.

The update seems to have deleted the seed. Asking me to create or restore a wallet.
 I do not have the backup.

**Comment by danjm** [comment]
@nostitos have you updated on multiple browsers and is it "Asking me to create or restore a wallet" on multiple browsers?

The seed is probably not deleted, but maybe your browser data is corrupted somehow.

If you are interested, we could get on a zoom call sometime this week to try to understand what has happened to your extension data.

**Comment by DockedFerret800** [comment]
> use Chrome stable

Can you submit update to Edge Add-ons as well? I'm experiencing the same problem.

**Comment by mmmro** [comment]
> @nostitos have you updated on multiple browsers and is it "Asking me to create or restore a wallet" on multiple browsers?
> 
> The seed is probably not deleted, but maybe your browser data is corrupted somehow.
> 
> If you are interested, we could get on a zoom call sometime this week to try to understand what has happened to your extension data.

has there been any update on this because this is what happened to me, pretty much exactly.

**Comment by rlarbac** [comment]
The same problem is happening to me. I am using a firefox 122.0 and Metamask is loading forever... By now, Metamask extenssion in Firefox browser is completely useless..

**Comment by jeffbzs** [comment]
@danjm how's it going with the solution to my problem?

**Comment by nostitos** [comment]
I can't do any more testing on my end since I created a new seed. The data
was gone after the update.

If I were someone affected with money on the line I'd backup whatever data
is in the extension before they push an update that might clear it out.

**Comment by digitalnomad91** [comment]
I'm having this exact same problem in Firefox....

**Comment by cclobo2** [comment]
same exact error here as reported in firefox

**Comment by cclobo2** [comment]
````
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:2889
Removing unpermitted intrinsics runtime-lavamoat.js:4079:15
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/popup.html
use-snow.js:23:14
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/popup.html
use-snow.js:23:14
Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). runtime-lavamoat.js:10114:15
Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). runtime-lavamoat.js:4381:30
Uncaught (in promise) Error: An unexpected error occurred
undefined
Uncaught (in promise) Error: An unexpected error occurred
undefined
SES_UNHANDLED_REJECTION: (Error#1) sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6929
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
Error#1: An unexpected error occurred sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    logError moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6890
    logSubErrors moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6833
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6931
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
<empty string> sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    logError moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6912
    logSubErrors moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6833
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6931
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
SES_UNHANDLED_REJECTION: (Error#2) sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6929
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
Error#2: An unexpected error occurred sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    logError moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6890
    logSubErrors moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6833
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6931
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
<empty string> sentry-install.js:1:693
    t moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    _ moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/sentry-install.js:1
    logError moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6912
    logSubErrors moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6833
    levelMethod moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:6931
    handleRejection moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7285
    finalizeDroppedPromise moz-extension://6b7107bc-708b-4c4a-9cbc-0abd14ff7c20/runtime-lavamoat.js:7058
```

Firefox log in case it helps

**Comment by justinasfour04** [comment]
Same issue happening on Brave right now

**Comment by xuyenvuong** [comment]
Same issue with Brave and MM v11.7.2. Tried to disable/enable the extension, restart browser, restart PC, still not working. I didn't try to reinstall MM due to the hassle.

**Comment by danjm** [comment]
@justinasfour04 @xuyenvuong Make sure to update to the latest version of MetaMask. Anyone experiencing this problem on Chrome and Brave over the past 3 weeks has fixed it by updating to v11.7.5 or later.

**Comment by justinasfour04** [comment]
@danjm how do I force an update?

**Comment by xuyenvuong** [comment]
> @justinasfour04 @xuyenvuong Make sure to update to the latest version of MetaMask. Anyone experiencing this problem on Chrome and Brave over the past 3 weeks has fixed it by updating to v11.7.5 or later.

Thank you @danjm . Will do.

**Comment by xuyenvuong** [comment]
> @danjm how do I force an update?

You can right click on the extension icon, then select `Manage extension`,  Next, turn on the "Developer mode", then click update. After the update, you can now log back into MM.

**Comment by cryptodigi** [comment]
got this issue on mm version 11.11.0 please deploy another update

**Comment by justinasfour04** [comment]
Now I have a stuck approval on a transaction and my settings are greyed out I can't use metamask now on my brave browser

**Comment by ExploreCrypto** [comment]
any fix for this; I have not had access to metamask on firefox for several weeks ; same stuck loading; have version 11.10.1

**Comment by cryptodigi** [comment]
<html>
<body>
<ol class="children body issue-kind-page-error expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding-left: calc(var(--issue-indent) + 43px); border-bottom: 1px solid var(--sys-color-divider); padding-top: 6px; position: relative; padding-bottom: 26px; padding-right: 8px; display: block; color: rgb(31, 31, 31); font-family: &quot;Segoe UI&quot;, tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent" aria-posinset="1" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><devtools-markdown-view style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="message" style="line-height: 20px; font-size: 14px; color: var(--override-markdown-view-message-color,--sys-color-token-subtle); margin-bottom: 4px; user-select: text;"><p style="margin-bottom: 16px; margin-block-start: 2px;">The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">To solve this issue, avoid using<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">eval()</code>,<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">new Function()</code>,<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">setTimeout([string], ...)</code><span> </span>and<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">setInterval([string], ...)</code><span> </span>for evaluating strings.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">If you absolutely must: you can enable string evaluation by adding<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">unsafe-eval</code><span> </span>as an allowed source in a<span> </span><code style="color: var(--sys-color-on-surface); font-size: 12px; user-select: text; cursor: text; background: var(--sys-color-surface1);">script-src</code><span> </span>directive.</p><p style="margin-bottom: 16px; margin-block-start: 2px;">⚠️ Allowing string evaluation comes at the risk of inline script injection.</p></div></devtools-markdown-view></li><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="always-parent parent expanded affected-resources-label" aria-expanded="true" aria-posinset="2" aria-setsize="3" style="box-sizing: border-box; min-width: 0px; min-height: 16px; margin-top: 5px; font-size: 10px; font-weight: 500; letter-spacing: 0.06em; text-transform: uppercase; color: var(--sys-color-on-surface); display: flex; text-overflow: ellipsis; white-space: normal; position: relative; align-items: flex-start;">RISORSE INTERESSATE</li><ol class="children expanded affected-resources" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 3px 0px 0px; position: relative; user-select: text; display: block;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" class="parent expanded" aria-expanded="true" aria-posinset="1" aria-setsize="1" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start; margin-top: 0px; padding: 2px 5px 0px; background: var(--sys-color-cdt-base-container);"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span><div class="affected-resource-label" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-size: 12px; line-height: 18px; color: var(--sys-color-on-surface); position: relative; cursor: pointer;">2 istruzioni</div></li><ol class="children expanded" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; list-style-type: none; padding: 6px 0px 9px 5px; display: block; background: var(--sys-color-cdt-base-container); margin-bottom: 10px;"><li jslog="TreeItem; parent: parentTreeItem" role="treeitem" tabindex="0" class="selected" aria-selected="true" style="box-sizing: border-box; min-width: 0px; min-height: 16px; text-overflow: ellipsis; white-space: normal; position: relative; display: flex; align-items: flex-start;"><span class="tree-element-title" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"></span>
Posizione della sorgente | Istruzione | Stato
-- | -- | --
runtime-lavamoat.js:10114 | script-src | bloccato
runtime-lavamoat.js:4381 | script-src | bloccato

</li></ol></ol></ol>
</body>
</html>

**Comment by cryptodigi** [comment]
> @justinasfour04 @xuyenvuong Make sure to update to the latest version of MetaMask. Anyone experiencing this problem on Chrome and Brave over the past 3 weeks has fixed it by updating to v11.7.5 or later.

not true, still same issue on 11.12.4

**Comment by Ess3ntial** [comment]
still experiencing the same infinite load on 11.12.4 on firefox 124.0.1 (64-bit)

**Comment by cryptodigi** [comment]
same problem on 11.13.1

**Comment by cryptodigi** [comment]
> Issue present on Ubuntu Firefox v124 and metamask 11.12.4 Infinite load unable to do anything to backup

hi man lol look like they not doing anything to solve this

**Comment by Carlosdvp** [comment]
Same issue on Firefox developer edition v126 (latest), Metamask was working fine for a while and then today the issue appeared. Happened to me once already, had to re-install metamask and import wallet again. Would be nice if we didn;t have to do this just to use the wallet in firefox.

**Comment by gauthierpetetin** [comment]
Hi all, is anyone still experiencing this issue with latest version of MetaMask?
If so, can you please share some error logs with us? Thanks

**Comment by sah543** [comment]
> Hi all, is anyone still experiencing this issue with latest version of MetaMask? If so, can you please share some error logs with us? Thanks

metamask updated few days ago. infinite loading screen. v11.16.5

![image](https://github.com/MetaMask/metamask-extension/assets/63679132/bc3a2209-c0db-436c-8c37-bf7b75bfcee9)

**Comment by trydex** [comment]
Same issue.
![image](https://github.com/MetaMask/metamask-extension/assets/20781342/fe7a1201-bbe8-4ba5-970e-cb6620f04500)

**Comment by turtlenice** [comment]
Metamask 11.16.14 + Chrome 126.0.6478.127 + MacOS 11.7.0
![mm-2](https://github.com/MetaMask/metamask-extension/assets/169300765/199a7523-b3af-4701-ae5c-29be005a21df)

**Comment by cryptodigi** [comment]
chrome on win 10 

![image](https://github.com/MetaMask/metamask-extension/assets/46853966/5733411f-e1e8-47bf-bee9-415d0b3a3a66)

![image](https://github.com/MetaMask/metamask-extension/assets/46853966/7b731627-a670-4171-a0d7-65f78d793f65)

**Comment by puzzle-rusher** [comment]
Firefox, macos, the same bug. Extencion reinstalling helps, but I don't want to do this every time.

**Comment by danjm** [comment]
Thanks @cryptodigi @turtlenice 

It looks like you both have a different problem than most others here are experiencing. With the error logs you have shared, we may actually be able to solve that problem. I will report back after investigating today

**Comment by danjm** [comment]
For anyone who hits the problem on firefox, where there is a "unexpected error occured" error in the console, you may be able to recover without having to reinstall by following the instructions in
https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1012084136 and the follow up comment https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1019317043

**Comment by trydex** [comment]
> For anyone who hits the problem on firefox, where there is a "unexpected error occured" error in the console, you may be able to recover without having to reinstall by following the instructions in [#9196 (comment)](https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1012084136) and the follow up comment [#9196 (comment)](https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1019317043)

Thanks for the link. [Renaming the file](https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-2002042848) helped me.

**Comment by Untouchable2k** [comment]
> > Hi all, is anyone still experiencing this issue with latest version of MetaMask? If so, can you please share some error logs with us? Thanks
> 
> ![metamaskerror](https://private-user-images.githubusercontent.com/15801157/343927411-e99e24af-0190-4983-b74e-b18e6b5e78fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjQwOTcsIm5iZiI6MTcyMTMyMzc5NywicGF0aCI6Ii8xNTgwMTE1Ny8zNDM5Mjc0MTEtZTk5ZTI0YWYtMDE5MC00OTgzLWI3NGUtYjE4ZTZiNWU3OGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE3Mjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNDRkYWU2MTU5MmFiNjlhYWJhNmJiY2E5MDMyNjI2ZWJhNTRlZGUyNzMzZTI4M2MzNDRmNWJiNDQwNWFkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EOvJS49jegofcM5I7F6SMfp9O73O_Dp5L6ulgX_J-GU) Still have this issue. Please assist

Still need help with resolving this for Linux OS

**Comment by MarcusWentz** [comment]
This issue still exists and should be considered high priority.

**Comment by MarcusWentz** [comment]
On Firefox, I got Metamask's Internal UUID from the following URL:
```
about:debugging#/runtime/this-firefox
```
When I attempt to access Metamask directly in a new tab with this URL:
```
moz-extension://<INTERNAL_UUID>/home.html#
```
I see the same loading issue. 

Maybe this is related to the Internal UUID being incorrect which needs to be updated

https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-2002042848

?

**Comment by harisbeha** [comment]
I started getting the infinite loading issue two days ago on Firefox 129.0.2 and Version 12.0.6. 

Attempted the file-renaming approach some have mentioned with no luck. 

I thought maybe it was a temporary issue sending analytics to Sentry (which has led to hard-to-debug issues on some production systems I managed in the past). It looks like the Vault approach has been deprecated and made not possible for some time with the lava-moat sandbox additions. Normally this would be fine since this isn't my main wallet, but still really inconvenient. 

![1](https://github.com/user-attachments/assets/2dbf1457-7442-47ce-98a0-22ddf1de5be3)
![2](https://github.com/user-attachments/assets/9300de40-dc7b-40b3-8112-6aa0fcf017b1)
![3](https://github.com/user-attachments/assets/fd75d4f7-7c7c-42eb-bc1d-76a0921d3cd8)

**Comment by ZKBitcoinToken** [comment]
Happened again on a Ubuntu machine of mine that got restarted when it got stuck and metamask was open.  Infinite load again.  FIX THIS

**Comment by jhhuh** [comment]
I am experiencing the same symptom started today. I'm on firefox (129.0, NixOS-24.05) with MetaMask (12.0.6).

**Comment by maxikgreat** [comment]
Facing this issue in chrome extension, version 12.3.1, infinite loading just right away i click on extension

**Comment by wslyvh** [comment]
Same issue. Also see #27555 (not solved)

v12.0.6 on Firefox / Linux
Can't open or do anything with Metamask. It just keeps loading

**Comment by vanthome** [comment]
Same issue here on FF under Linux.

**Comment by tip2663** [comment]
same issue, FF on windows

**Comment by mvrvelous** [comment]
Had this problem with Firefox. So I installed it on LibreWolf. Could login again. But now the problem also appeared on LibreWolf. Very random.

**Comment by abra1l** [comment]
more and more ppl quit using mm everyday for the past 3 yrs and you cant even fix one single issue thats been going on for half a year. @danjm are yall even working on this or you completely abandoning sinking ship? 
same issue mm version 12.6, chrome version 130.0.6723.117, macos 14.5, had this issue for last 2 weeks or more

**Comment by abra1l** [comment]
MM updated to 12.6.1 today, nothing changed

**Comment by mvrvelous** [comment]
> MM updated to 12.6.1 today, nothing changed

It happened again to me for the 3rd time. I'm going to import my wallet to Phantom. I'm done with this.

**Comment by abra1l** [comment]
@danjm

**Comment by cryptodigi** [comment]
My problem with infinite loading was fixed in september

Il lun 18 nov 2024, 07:55 noname ***@***.***> ha scritto:

**Comment by faithsloan** [comment]
exact same problem here. Chrome Version 131.0.6778.86 (Official Build) (64-bit)
with Metamask 12.7.2

Open extension and get the metamask logo and that irritating circle going around and around forever

cleared cache. disabled all extensions. shutdown browser. still the same. shut down computer. still the same. tried everything recommended in discussion forums except uninstall and re-install. same...same...
i have 20 separate accounts. shouldn't have to re-install.

when will this bug be fixed, boys?

i ported everything over to trust wallet and rabby wallet successfully. But I'd like to use mm for easy dapp integration usage

fix this

**Comment by danjm** [comment]
@cryptodigi What happened that caused your loading problem to be fixed in September? And how long were you experiencing it before then?

**Comment by vpoulailleau** [comment]
Same here with Firefox 133.0.0 under Linux.

Here is my console export (partially in French… ping me if you need help in translation):
```
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:2907
Removing unpermitted intrinsics runtime-lavamoat.js:4223:15
Removing intrinsics.Uint8Array.fromBase64 sentry-install.js:1:693
Removing intrinsics.Uint8Array.fromHex sentry-install.js:1:693
Removing intrinsics.%InitialMath%.f16round sentry-install.js:1:693
Removing intrinsics.%SharedMath%.f16round sentry-install.js:1:693
Removing intrinsics.%Uint8ArrayPrototype%.setFromBase64 sentry-install.js:1:693
Removing intrinsics.%Uint8ArrayPrototype%.setFromHex sentry-install.js:1:693
Removing intrinsics.%Uint8ArrayPrototype%.toBase64 sentry-install.js:1:693
Removing intrinsics.%Uint8ArrayPrototype%.toHex sentry-install.js:1:693
Removing intrinsics.%FunctionPrototype%.apply.prototype sentry-install.js:1:693
Tolerating undeletable intrinsics.%FunctionPrototype%.apply.prototype === undefined sentry-install.js:1:693
Removing intrinsics.%FunctionPrototype%.bind.prototype sentry-install.js:1:693
Tolerating undeletable intrinsics.%FunctionPrototype%.bind.prototype === undefined sentry-install.js:1:693
InstallTrigger est obsolète et sera supprimé prochainement. runtime-lavamoat.js:12786:21
onmozfullscreenchange est obsolète. runtime-lavamoat.js:12786:21
onmozfullscreenerror est obsolète. runtime-lavamoat.js:12786:21
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/background.html
use-snow.js:23:14
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/background.html
use-snow.js:23:14
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:10422:15
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:4525:30
Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more. sentry-install.js:1:693
unreachable code after return statement background-2.js:1:542714
WARNING: Missing strong random number source sentry-install.js:1:693
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) 4 runtime-lavamoat.js:6527:41
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
SES_UNHANDLED_REJECTION: (Error#1) sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7134
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
Error#1: DataCloneError: The object could not be cloned. sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7087
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
<empty string> sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7109
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
SES_UNHANDLED_REJECTION: (Error#2) sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7134
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
Error#2: DataCloneError: The object could not be cloned. sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7087
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
<empty string> sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7109
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
SES_UNHANDLED_REJECTION: (Error#3) sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7134
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
Error#3: DataCloneError: The object could not be cloned. sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7087
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
<empty string> sentry-install.js:1:693
    t moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    _ moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/sentry-install.js:1
    logError moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7109
    logSubErrors moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7030
    levelMethod moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7136
    handleRejection moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7584
    finalizeDroppedPromise moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/scripts/runtime-lavamoat.js:7357
L’API de journalisation de la console (console.log, console.info, console.warn, console.error) a été désactivée par un script sur cette page.
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:2907
Removing unpermitted intrinsics runtime-lavamoat.js:4223:15
InstallTrigger est obsolète et sera supprimé prochainement. runtime-lavamoat.js:12786:21
onmozfullscreenchange est obsolète. runtime-lavamoat.js:12786:21
onmozfullscreenerror est obsolète. runtime-lavamoat.js:12786:21
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/home.html#
use-snow.js:23:14
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/home.html#
use-snow.js:23:14
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:10422:15
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:4525:30
Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more. sentry-install.js:1:693
unreachable code after return statement ui-0.js:1:50367
unreachable code after return statement ui-0.js:1:50875
unreachable code after return statement ui-0.js:1:54590
unreachable code after return statement ui-10.js:26:76231
unreachable code after return statement ui-10.js:26:81170
unreachable code after return statement ui-10.js:26:83489
WARNING: Missing strong random number source sentry-install.js:1:693
The object notation for `createSlice.extraReducers` is deprecated, and will be removed in RTK 2.0. Please use the 'builder callback' notation instead: https://redux-toolkit.js.org/api/createSlice sentry-install.js:1:693
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
SES_UNHANDLED_REJECTION: (Error#1) sentry-install.js:1:693
Error#1: DataCloneError: The object could not be cloned. sentry-install.js:1:693
<empty string> sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (Error#2) sentry-install.js:1:693
Error#2: DataCloneError: The object could not be cloned. sentry-install.js:1:693
<empty string> sentry-install.js:1:693
Ouverture de about:blank
Ouverture de moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/background.html
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:2907
Removing unpermitted intrinsics runtime-lavamoat.js:4223:15
InstallTrigger est obsolète et sera supprimé prochainement. runtime-lavamoat.js:12786:21
onmozfullscreenchange est obsolète. runtime-lavamoat.js:12786:21
onmozfullscreenerror est obsolète. runtime-lavamoat.js:12786:21
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/background.html
use-snow.js:23:14
Snow detected a new realm creation attempt in MetaMask. Performing scuttling on new realm. 
Window moz-extension://8001a814-4b02-417a-9bf6-9b5481bf4faa/background.html
use-snow.js:23:14
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:10422:15
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) runtime-lavamoat.js:4525:30
Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more. sentry-install.js:1:693
unreachable code after return statement background-2.js:1:542714
WARNING: Missing strong random number source sentry-install.js:1:693
Content-Security-Policy : Les paramètres de la page ont empêché l’exécution d’une « eval » JavaScript (script-src) car elle enfreint la directive suivante : « script-src 'self' 'wasm-unsafe-eval' » (la valeur 'unsafe-eval' est manquante) 4 runtime-lavamoat.js:6527:41
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
Uncaught (in promise) Error: DataCloneError: The object could not be cloned.
undefined
SES_UNHANDLED_REJECTION: (Error#1) sentry-install.js:1:693
Error#1: DataCloneError: The object could not be cloned. sentry-install.js:1:693
<empty string> sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (Error#2) sentry-install.js:1:693
Error#2: DataCloneError: The object could not be cloned. sentry-install.js:1:693
<empty string> sentry-install.js:1:693
SES_UNHANDLED_REJECTION: (Error#3) sentry-install.js:1:693
Error#3: DataCloneError: The object could not be cloned. sentry-install.js:1:693
<empty string> sentry-install.js:1:693
```

**Comment by username999111** [comment]
Hello, I spent the last 8 hours today logging into Metamask and I cant (Chrome & Mac).

I used to have this infinite loading issue for the last 6 months, but could always get it resolved by just trying 20 times or so.

It is absolutely urgent that this gets fixed, I can't access funds and am behind on payments etc. 

absolutely dont know what to do anymore, have tried every single thing i could find online and nothing worked

**Comment by vpoulailleau** [comment]
> Hello, I spent the last 8 hours today logging into Metamask and I cant (Chrome & Mac).

@username999111 I tried with another browser (brave), installed Metamask, and restored my account with my SRP. Everything works great in the second browser while I still have the issue with Firefox

**Comment by username999111** [comment]
Yes thanks, I did the same eventually -- works in Brave, but didnt want to go through process with restoring account etc but had no choice. Will finally switch to another wallet, absolute disgrace this known bug (for years) negatively impacts so many people.

**Comment by mvrvelous** [comment]
> > Hello, I spent the last 8 hours today logging into Metamask and I cant (Chrome & Mac).
> 
> @username999111 I tried with another browser (brave), installed Metamask, and restored my account with my SRP. Everything works great in the second browser while I still have the issue with Firefox

This worked for me also but then after a while it started happening in the other browser also. The browser is LibreWolf which is based on Firefox tho.

**Comment by Takayuki-Suzuki** [comment]
Here's my work around.

https://github.com/MetaMask/metamask-extension/issues/27555#issuecomment-2407365016

**Comment by takadr** [comment]
This worked for me:
https://github.com/MetaMask/metamask-extension/issues/27555#issuecomment-2407365016

**Comment by Virus-Axel** [comment]
Hi, I ran into this. I used metamask for a couple of weeks. I bought a bunch of crypto and metamask does not work anymore now. Is there a solution. Can I recover the private key?

**Comment by Hinted-tech** [comment]
> Hi, I ran into this. I used metamask for a couple of weeks. I bought a bunch of crypto and metamask does not work anymore now. Is there a solution. Can I recover the private key?

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Metamask Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by MarcusWentz** [comment]
Looks like a phishing scam comment
https://github.com/MetaMask/metamask-extension/issues/22533#issuecomment-2526205965
from
@Hinted-tech
Can we delete this from the issue thread?

**Comment by gauthierpetetin** [comment]
@Hinted-tech 's message was a phishing scam. His comment is now deleted.

**Comment by takadr** [comment]
No, I'm not a scammer, but I understand that it looked like a scam.
The URL on the comment mentioned above is the extension setting for Metamask.
`nkbihfbeogaeaoehlefnkodbefgpgknn` is a extension id for Metamask.

The point is that once you open Metamask extension on the secret window, the issue was solved for me (Chrome).
I'm not sure why but something related to local storage or something.

**Comment by Virus-Axel** [comment]
Tip, take a backup of the whole firefox folder before trying things.

I extracted the vault from db files and decrypted it using my passkey.

**Comment by owoerator** [comment]
I've been experiencing this issue for the past week couple weeks, only started trying to fix it about a week ago bc I need access and was hoping it would just un-fuck itself (it didn't). Can't get to my money and it ain't great.
Firefox, infinite loading. Little spinning icon, doesn't load up.
I've had a support chat going, and that solution isn't panning out, seems more related to this. Seriously hoping this gets fixed soon and pushed to Firefox apps for an update.

> Tip, take a backup of the whole firefox folder before trying things.
> 
> I extracted the vault from db files and decrypted it using my passkey.

Speaking of, I tried to recover my Secret Phrase with the method provided here: https://support.metamask.io/managing-my-wallet/secret-recovery-phrase-and-private-keys/how-to-recover-your-secret-recovery-phrase/
but I haven't been able to due to getting this when I paste the data retrieval command in the console:
`Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode.`

If anyone can at least help me fix this, than maybe I can get my SRP back. Sucks I can't find it when I thought I backed it up.
Would really appreciate the help

**Comment by faithsloan** [comment]
I have all of my 12 words and private keys for at least a dozen wallets in
metamask. Thank God.

Metamask is a royal shit show.

I'm using tokenpocket and rabby wallets now.

This is ridiculous. Your update broke your software, PERIOD!!!

Folks, if you have your 12 words. Then install metamask on another device.
Import with 12 words. It will only give you the first wallet. So do it
again, it will give you your 2nd account. Do it again and again and you
will get each of your wallet accounts.

Get the private keys of all of your accounts. Then USE ANOTHER wallet
provider and import using private keys.

Metamask is old, insecure, centralized, data collecting, technology. Kill
it.

**Comment by danjm** [comment]
> Speaking of, I tried to recover my Secret Phrase with the method provided here: https://support.metamask.io/managing-my-wallet/secret-recovery-phrase-and-private-keys/how-to-recover-your-secret-recovery-phrase/
but I haven't been able to due to getting this when I paste the data retrieval command in the console:
Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode.

@owoerator Those instructions are partially outdated. If you follow those instructions, but instead of this code:

```
chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})
```

paste this command in the console: `console.log((await stateHooks.getPersistedState()).data.KeyringController.vault)`

You will see output like this:
```
'{"data":"1+W+h/v5Qb3y4G5Sy9IXoYxyeyx5AAHVuKMOsn/d4RV6YaqogKihw62Cg53qir61y+HWDzOu5JrQcmpIuh8O9de/pS7pxpNaqMFdQL4V70QTOV9kFafX3D3zsJuWgQ1yuRzqLxg3Zn1DJ8uZzSlZM8YoJykeHnvvhRlnKkhxgiRJESuq1a9nzeen+LMXXycg/BW/NGrwRHwK/Pkq3RTq4xGk3EEjkrC2nV4DxLtQRkNkLpWFJkEH18hb8EOx51wx8WDHTxmxTulXPyV9v/g2hG8dbGfI6AnOPObXy+TQ/nD5ihtNDm9J9q8/PM7/VItPeC7mH6uTN+p9wYUqidA9p1DGU9b0Nyp3emowe/MQyDd16pNhpxi9Ql/VSzNjHkKFR3MmVuX/wsZwHUOPuXTMTAjBsXVHhCMrEfdN4plQioynLPOruEroTlbow3MyrOsSjJAkxuFM7PedqY1Qgi0S/lM0F62NfnLR/8Z3LnPHw3nKpwQW+xidTLoXZKHOBC/b4EWq+Es7Q=","iv":"eSn/DG2moTx0/jKy1J+MQw==","keyMetadata":{"algorithm":"PBKDF2","params":{"iterations":600000}},"salt":"iNp1vcWi5lL8iOHnzXfBLTdtKLO5oN4qPIVgyM9Ta8o="}'
```

You can then follow the instructions to the vault decryptor page, paste it in the "Paste text" field and enter your password to decrypt the vault.

**Comment by jkdi** [comment]
> Hi [@danjm](https://github.com/danjm) looks like I am now having the issue of the infinite spinning loading screen, probably triggered with today's 12.6.2 update of Metamask in Firefox.
> 
> MM was working perfectly fine yesterday in Firefox, and no new browser updates or OS updates were done between now and then.
> 
> Problem: After entering passwork into MM extension, MM gets stuck on an infinite spinning wheel and ultimately kicks me back out to log in window.
> 
> MM version: 12.6.2 (last updated 12/16/2024) Firefox version: 133.0.3 Windows 10
> 
> ![Image](https://github.com/user-attachments/assets/87cd2233-48a3-488b-aa4e-d536a34ec2e1) ![Image](https://github.com/user-attachments/assets/a1750169-3fd1-47f1-a331-847338bdea47)

have exactly the same issuse with this 12.6.2 Version of MM! 


![Image](https://github.com/user-attachments/assets/b5084dc9-bf72-4b8a-a999-feaeed46bfe0)

**Comment by jkdi** [comment]
please fix it ASAP! i need my funds!!

**Comment by owoerator** [comment]
> console.log((await stateHooks.getPersistedState()).data.KeyringController.vault)
I really really appreciate the help btw. I saw your post and was really happy I might have a solution to get my SRP, but kinda waited bc I've had some severe lifetroubles to work through. I sat down just now to try and decrypt it for the holidays.
Unfortunately I ran into this error when I inputted this code you gave: `console.log((await stateHooks.getPersistedState()).data.KeyringController.vault)`
The return error:
![Image](https://github.com/user-attachments/assets/f16aa30a-9e4d-49b6-b79f-e61f31ea64d2)

I had sat down and loaded the previous metamask window I was using before and put the "Console.log" code into that prior to the first image. After, I just killed that tab and repeated the process to try fresh and got the first image.
Here's what was there from the prior two code Ctrl+V's I threw into the console (denoted by red square, it doesn't show them, I assume that's bc I put a new one in)
![Image](https://github.com/user-attachments/assets/42cd9667-fecf-4f5a-a37f-54bdb7914f1c)
Sorry for the lack of expertise, but I hope this helps. If you have any ideas or a solution to get my metamask data still, I'd be eternally grateful. I'm running the latest Vers. of Firefox: Version 133.0.3 (64-bit)

Hope we all get a solution to these troubles soon, must be a headache trying to figure it out.

**Comment by owoerator** [comment]
@danjm Sorry not sure how github @s work, I qoute replied but didn't @ originally and edited it in after, so I'm just @ing again. Thanks for the help

**Comment by vpoulailleau** [comment]
> please fix it ASAP! i need my funds!!

@jkdi The workaround is https://github.com/MetaMask/metamask-extension/issues/22533#issuecomment-2508902063

**Comment by jkdi** [comment]
> > please fix it ASAP! i need my funds!!
> 
> [@jkdi](https://github.com/jkdi) The workaround is [#22533 (comment)](https://github.com/MetaMask/metamask-extension/issues/22533#issuecomment-2508902063)

i see this, but i dont have an backup of my 12 words recovery phrase so i must recover this first. here on github is a great phyton script to do this with firefox browsers: 

https://github.com/JesseBusman/FirefoxMetamaskWalletSeedRecovery

**Comment by jcalv13** [comment]
@danjm Same issue for me in metamask 12.6.2. The issue was present in firefox 133.0.3 & the previous version, as it has persisted for me after updating. Prior to the current version I found that on a whim Metamask extension would work properly, but now for 3 days running I have had the same perpetual loading. I would like to add I have not had any system crashes/updates to my IOS (Mac 12.6.6). 
I have previously had the stuck on blank screen error which was fixed by renaming the metamask file in the idb folder, however this is not the same issue/solution. 
I would also like to add (although none of your team seem to believe me) that my SRP does not restore my metamask wallet. I have the phrase written down & I have used the vault decryptor to confirm it is correct. However when I try to restore the wallet in chrome, it resolves an unknown wallet. I understand I have to add account to resolve my multiple wallets however this does not bring up ANY of my wallets from the firefox browser. I also understand imported wallets will not be restored but still the SRP does not restore any of my original wallet addresses. I would be happy to video chat with metamask team to prove this (once I can regain current access & remove any currency in the wallets). 

I have attached the file of the console error
[console-export-2025-1-3_12-9-19.txt](https://github.com/user-attachments/files/18299681/console-export-2025-1-3_12-9-19.txt)

**Comment by jcalv13** [comment]
(Temporary) SOLUTION: https://github.com/MetaMask/metamask-extension/issues/29332 - at least for me in firefox browser. 

Open incognito window 
Disable & re-enable metamask extension 
Log into more obscure network (for me I used zkSync)

**Comment by siberian1967** [comment]
Incognito fix worked for me in Chrome as well. Open once in Incognito, and regular browse mode works from that point forward.

**Comment by kardus** [comment]
I'm encountering this issue and the private window solution does _not_ work for me

**Comment by kardus** [comment]
> > I'm encountering this issue and the private window solution does _not_ work for me
> 
> You must try select obscure network like linea , disable MM, close tab, and then re-enable in NEW incognito tab [solution](https://github.com/MetaMask/metamask-extension/issues/29332)

I can't enter my decryption passphrase or interact with metamask in any fashion, I get the spinning circle + metamask logo as soon as I press the addon button, no prompt to enter pw or click on anything. I'm getting this behaviour on both macOS and windows as well.

**Comment by hodlmybeer1** [comment]
With today's Firefox update 134.0.1, Metamask is once again unusable with the infinite spinning wheel after entering password. Insane that this keeps happening.

**Comment by DigDataSteve** [comment]
I have metamask version 12.6.2 that is running on Firefox, which is updated and metamask will not load, it just shows spinning icon. WTF. What is the solution to this problem????

<img width="892" alt="Image" src="https://github.com/user-attachments/assets/bd3fcccf-c040-4862-9084-5d3904e0bc8c" />

**Comment by jcalv13** [comment]
For everyone experiencing infinite spinning screen, try this solution. I personally have it bookmarked because it happens frequently to me. 
https://github.com/MetaMask/metamask-extension/issues/9196#issuecomment-1012084136 - Scroll down you will see a comment marked solution, 1 comment below that you find a very helpful extra bit of info from "mackwage" which removes the guesswork involved in renaming the file.

**Comment by faithsloan** [comment]
it has been over 5-6 months and still can't access metamask

sentry-install.js:1 Event handler of 'error' event must be added on the
initial evaluation of worker script.
sentry-install.js:1 Event handler of 'unhandledrejection' event must be
added on the initial evaluation of worker script.
runtime-lavamoat.js:4223 Removing unpermitted intrinsics
sentry-install.js:1 Property eval will not be hardened because it is
scuttled by LavaMoat protection. Visit
https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
sentry-install.js:1 WARNING: Missing strong random number source
sentry-install.js:1 This browser doesn't support requestAnimationFrame.
Make sure that you load a polyfill in older browsers.
https://fb.me/react-polyfills
sentry-install.js:1 This browser doesn't support cancelAnimationFrame. Make
sure that you load a polyfill in older browsers.
https://fb.me/react-polyfills
sentry-install.js:1 SCRIPTS IMPORT COMPLETE in Seconds: 1.914
sentry-install.js:1 Running migration 132...
sentry-install.js:1 Migration 132 complete
sentry-install.js:1 Running migration 133...
sentry-install.js:1 Migration 133 complete
sentry-install.js:1 Running migration 133.1...
sentry-install.js:1 Migration 133.1 complete
sentry-install.js:1 Running migration 133.2...
sentry-install.js:1 Migration 133.2 complete
common-1.js:1 Uncaught (in promise) Error: NetworkController state is
invalid: `selectedNetworkClientId` '45b02512-3ca4-43ff-8ce1-8a90b2a6ab4f'
does not refer to an RPC endpoint within a network configuration
2
background-7.js:1 Uncaught (in promise) Error: NetworkController state is
invalid: `selectedNetworkClientId` '45b02512-3ca4-43ff-8ce1-8a90b2a6ab4f'
does not refer to an RPC endpoint within a network configuration
﻿

**Comment by agupagu** [comment]
<img width="610" alt="Image" src="https://github.com/user-attachments/assets/484deb5c-1960-4348-885a-e8b689dba4cc" />
<img width="613" alt="Image" src="https://github.com/user-attachments/assets/68e15420-6d84-490c-b00f-e216c7e03a95" />


Including this here as I am trying to automate a local build with Browser-Use which uses playwright as its backend

**Comment by alexewsv** [comment]
I've faced this issue, any one advise me how to get out of this?
thank you

**Comment by rilweezy1200** [comment]
![Image](https://github.com/user-attachments/assets/1b33ac86-0bd6-4810-82f5-dc6c600c2a5c)

I get same error now, latest update to version 12.4.1 chrome, MM opens a new tab on startup by itself automatically and just stuck on that infinite loading screen page

**Comment by alecov** [comment]
Same error here on Brave Browser `[Version 1.78.94 Chromium: 136.0.7103.60 (Official Build) (64-bit)](https://brave.com/latest/)`

Been like this for a months. When I type the passwd it spins for eternity, then I lose patience, press F5 to refresh, type the password again and it opens. Horrible experience.

Same errors as all above, `sentry-install.js` bugs. What a mess.

**Comment by rebelinnovator** [comment]
<img width="1504" height="871" alt="Image" src="https://github.com/user-attachments/assets/e20f6109-78ff-4b0a-8a17-eebbbb3bed98" />
same error happen to me. 
anybody can help? It is really urgent for me.
if impossible, is there anyway to get private key or seed from chrome extension data??

**Comment by gauthierpetetin** [comment]
Hi @rebelinnovator, could you please go to chrome://extensions/, then disable and re-enable MetaMask to see if that resolves the issue? Also, what version of MetaMask extension are you using?

**Comment by davidmurdoch** [comment]
@rebelinnovator You need to update your browser. That error happens because I used an API that isn't available in your browser. Sorry for this! We're fixing this in the next release.

But still, you really do need to update your browser, it's not safe to use an outdated browser, and it is especially not safe to do so with a crypto wallet.

**Comment by ralyodio** [comment]
Its still happening on librewolf for me (kde/arch)
