### ISSUE TITLE
[Bug]: Unapproved transaction stuck, settings and other buttons disabled

### ISSUE THREAD

**Issue by justinasfour04** [MetaMask/metamask-extension#23401]
### Describe the bug

As I was trying to run a transaction earlier, I had approved it but when I checked metamask said that it was unapproved and when I try to reject it nothing happens. Now I have network, settings, and connected sites buttons greyed out. Metamask currently unusable.

### Screenshots/Recordings

<img width="214" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/6599551/72f2aa8e-69e9-4736-9092-8d1f03e7da3f">
<img width="83" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/6599551/54f5b465-bf60-4c49-9bf4-c9fed5fd8503">
<img width="159" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/6599551/a4c48038-bc48-4dea-a11f-c20d442df31b">

### Steps to reproduce

Not sure how to reproduce

### Version

11.11.4

### Build type

None

### Browser

Brave

### Operating system

MacOS

**Comment by thekoenekamp** [comment]
+1 - transaction in MetaMask is showing as unapproved, but when I check on Etherscan, it appears as successfully completed - and it is.

**Comment by Oblivion165** [comment]
Here's a video I made for reddit on how to create this bug. Please please fix it. I have to use metamask for my job and this bug makes me reinstall metamask hundreds of times a day.

https://youtu.be/bjI8x1zcB5o

**Comment by fenidik** [comment]
same

**Comment by davidcan** [comment]
same problem
![Screenshot 2024-03-12 192557](https://github.com/MetaMask/metamask-extension/assets/878261/5f1555e2-d079-4851-b53a-69043683debc)

**Comment by Overthetop123** [comment]
Same issue as well. And it is a doozy. Literally can’t do anything. This needs a solution quick sticks please

**Comment by lathaz32** [comment]
I've got the same issue. It's been essentially locked for 8 hours now, can't do anything

**Comment by notmycupofnft** [comment]
Having the same issue. Cannot change network, send/receive funds or go to settings. Account is **completely frozen now**

**Comment by yurbar** [comment]
The same issue, can't perform transaction in ETH net. All the transaction set to Unapproved immediately after press Confirm. And no record in etherscan

**Comment by Okz61** [comment]
All accounts stuck ! Any fix ??

**Comment by stableddd3** [comment]
same issue I am unable to access $50,000 in funds. please fix

**Comment by nick7000** [comment]
I had the same. You can unfreeze it by going through with any transaction on portfolio.metamsk.io. It will prompt you to change the network. Once you do, settings and network switch is unlocked.

**Comment by S1nPur1ty** [comment]
I can't even change from Network. WTF Metamask!

**Comment by npomfret** [comment]
Does anyone have a fix?

**Comment by achrafyhy** [comment]
Clear cache and go to MetaMask Portfolio website to switch networks and go on

**Comment by Bussi4Nicole** [comment]
… and do a restart 
Had same issue on Mac

**Comment by kreddington41** [comment]
> Clear cache and go to MetaMask Portfolio website to switch networks and go on

does not work

> A work-around is to not empty the wallet, leave a tiny bit of gas in there. It can be super small but has to be something.

not a work around because I purposefully left ETH in the wallet for this reason and this bug still occurred...

**Comment by kreddington41** [comment]
Has anybody come across a solution to this? I have a lot of ETH just stuck and it's not really a fun experiencing the idea of losing it all...

**Comment by kreddington41** [comment]
> Does anyone have a fix?

No, I don't think so. This bug is affecting all of my metamask accounts...

**Comment by kreddington41** [comment]
> I can't even change from Network. WTF Metamask!

same, please let me know if you come across a solution. Thank you

**Comment by Fegrnova** [comment]
Easiest fix is downloading any other wallet extension (like Rabby), importing metamask address private key (which you can access despite bug in metamask), disabling metamask in browser (in manage extensions section), sending any tx with Rabby on stuck network (avaxc in your case), then activating metamask again. This 100% fixes it but yeah, very annoying bug

The other way is uninstalling metamask and then entering your private key again, which is more trouble (as you will need to import all tokens etc.)

You can change the network by locking metamask, and changing it before entering password. Problem is clearing history affects only current network, and once you switch back to the original one you get stuck again.

Sometimes sending tx to the stuck address helps as well, either from other networking utilizing some cross chain tech, or from another address. Doing this with mainnet is expensive, with avaxc its cheap to try

**Comment by Fegrnova** [comment]
> Having the same issue. Cannot change network, send/receive funds or go to settings. Account is **completely frozen now**

I wrote it detail above

**Comment by Fegrnova** [comment]
> > I can't even change from Network. WTF Metamask!
> 
> same, please let me know if you come across a solution. Thank you

same to you sir

**Comment by S1nPur1ty** [comment]
This is ridiculous, I am not going to install something else to fix it temporarily. I need to see the Metamask devs fixing this stupid bug asap just like others!

**Comment by Fegrnova** [comment]
> This is ridiculous, I am not going to install something else to fix it temporarily. I need to see the Metamask devs fixing this stupid bug asap just like others!

This bug has been around for quite some time, with various circumstances causing it. So it's better to unfreeze your accounts until waiting for fix a lol

btw it does not happen that often, so fix is not that much of temporary. sending a tx with low eth remaining is what causes it mostly.

**Comment by ihorbond** [comment]
> Has anybody come across a solution to this? I have a lot of ETH just stuck and it's not really a fun experiencing the idea of losing it all...

bro Metamask is just an interface, you still have you private key. If you think this would make you lose your ETH you need to learn how Metamask and wallets alike work, for your own sake

**Comment by ihorbond** [comment]
Here's how I fixed mine: go to portfolio and do some other action that prompts MM to switch network. open metamask in expanded view so it's in its own tab and go to settings > advanced. now while in settings switch back to the network and account where tx is stuck. click reset activity. done. no need to clear cache or cookies.

**Comment by mamasd** [comment]
Right-click on the fox icon (the metamask wallet), then click on "Manage extension
 
 On the right corner, turn on "Developer mode". On the left, option will show up, please click on "Update".  
 
 Great! You can turn Dev mode off if you'd like, or leave it as that no worries. Now, turn off the option (shown in the image below) and then turn it back on,

![image](https://github.com/MetaMask/metamask-extension/assets/163781379/960c755c-e135-46c0-96c1-c825986f231a)

! Please go to settings, advanced, and click "Clear activity tab data".
On mobile, it might show up as "Reset account"

You can then try the transaction once more, let me know how it goes

**Comment by Oblivion165** [comment]
How is this not fixed yet? I provided that video that shows how to create this bug 7 days ago. I think they are keeping it around to boost their download numbers 😂

**Comment by jayow** [comment]
> Here's how I fixed mine: go to portfolio and do some other action that prompts MM to switch network. open metamask in expanded view so it's in its own tab and go to settings > advanced. now while in settings switch back to the network and account where tx is stuck. click reset activity. done. no need to clear cache or cookies.

I can confirm this solved the issue

**Comment by camconrad** [comment]
I've gotten it twice in the last week :/

**Comment by Thomas-Smets** [comment]
> Right-click on the fox icon (the metamask wallet), then click on "Manage extension
> 
> On the right corner, turn on "Developer mode". On the left, option will show up, please click on "Update".
> 
> Great! You can turn Dev mode off if you'd like, or leave it as that no worries. Now, turn off the option (shown in the image below) and then turn it back on,
> 
> ![image](https://private-user-images.githubusercontent.com/163781379/313508864-960c755c-e135-46c0-96c1-c825986f231a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzUwODksIm5iZiI6MTcxMDk3NDc4OSwicGF0aCI6Ii8xNjM3ODEzNzkvMzEzNTA4ODY0LTk2MGM3NTVjLWUxMzUtNDZjMC05NmMxLWM4MjU5ODZmMjMxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQyMjQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2VmMDNiMjVhNWY0NTFhNWFmN2JlMGM1MjA0OTJiMGI3ZDQ2Nzg2N2VhNThmYTY5OTdlMDU0MDQ0ZWQwMWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ymcBCdWfhq2DNwisSVqTBBGvcWPKAWImTw6ansUg0Do)
> 
> ! Please go to settings, advanced, and click "Clear activity tab data". On mobile, it might show up as "Reset account"
> 
> You can then try the transaction once more, let me know how it goes

This one worked for me, more specifically with the bridge function and then I could switch network:
https://portfolio.metamask.io/bridge

**Comment by Thomas-Smets** [comment]
> Here's how I fixed mine: go to portfolio and do some other action that prompts MM to switch network. open metamask in expanded view so it's in its own tab and go to settings > advanced. now while in settings switch back to the network and account where tx is stuck. click reset activity. done. no need to clear cache or cookies.

This one worked for me, more specifically with the bridge function and then I could switch network:
https://portfolio.metamask.io/bridge

**Comment by positr0nik** [comment]
> Right-click on the fox icon (the metamask wallet), then click on "Manage extension
> 
> On the right corner, turn on "Developer mode". On the left, option will show up, please click on "Update".
> 
> Great! You can turn Dev mode off if you'd like, or leave it as that no worries. Now, turn off the option (shown in the image below) and then turn it back on,
> 
> ![image](https://private-user-images.githubusercontent.com/163781379/313508864-960c755c-e135-46c0-96c1-c825986f231a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDc2MDgsIm5iZiI6MTcxMTYwNzMwOCwicGF0aCI6Ii8xNjM3ODEzNzkvMzEzNTA4ODY0LTk2MGM3NTVjLWUxMzUtNDZjMC05NmMxLWM4MjU5ODZmMjMxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNjI4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQ5YmY2NGZhODAyZWVmMmVjNWQ3ZjZlODJlZTJhNGQ5NjgwMDM0ZWFmMTRlYTQ2M2YxMDBmYmQxYjQ0YTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tm6y6kCeXKf1lrb8VxQIKAygwaJ9dz76i2ovVsR6Ud4)
> 
> ! Please go to settings, advanced, and click "Clear activity tab data". On mobile, it might show up as "Reset account"
> 
> You can then try the transaction once more, let me know how it goes

This worked for me thanks!

**Comment by mystman1234** [comment]
> Easiest fix is downloading any other wallet extension (like Rabby), importing metamask address private key (which you can access despite bug in metamask), disabling metamask in browser (in manage extensions section), sending any tx with Rabby on stuck network (avaxc in your case), then activating metamask again. This 100% fixes it but yeah, very annoying bug
> 
> The other way is uninstalling metamask and then entering your private key again, which is more trouble (as you will need to import all tokens etc.)
> 
> You can change the network by locking metamask, and changing it before entering password. Problem is clearing history affects only current network, and once you switch back to the original one you get stuck again.
> 
> Sometimes sending tx to the stuck address helps as well, either from other networking utilizing some cross chain tech, or from another address. Doing this with mainnet is expensive, with avaxc its cheap to try

This worked 👍

**Comment by iquitgithub** [comment]
> Here's how I fixed mine: go to portfolio and do some other action that prompts MM to switch network. open metamask in expanded view so it's in its own tab and go to settings > advanced. now while in settings switch back to the network and account where tx is stuck. click reset activity. done. no need to clear cache or cookies.

this solution solves my problem!

**Comment by issa-me-sush** [comment]
> it as that no worries. Now, turn off the option (shown in the image below) and then turn it back on,

this worked in my case when it was "unapproved" and i was not able to interact at all, not even the settings tab and also not able reject the trx , metamask just sucks

**Comment by kmatari** [comment]
the issue is not fixed. how is this bug closed? There is a very annoying bug in metamask and we see that it is closed! I updated my mm and no changes.

**Comment by saturn123** [comment]
This issue still exists and this is so annoying.

**Comment by Wolfson61** [comment]
> > Right-click on the fox icon (the metamask wallet), then click on "Manage extension
> > On the right corner, turn on "Developer mode". On the left, option will show up, please click on "Update".
> > Great! You can turn Dev mode off if you'd like, or leave it as that no worries. Now, turn off the option (shown in the image below) and then turn it back on,
> > ![image](https://private-user-images.githubusercontent.com/163781379/313508864-960c755c-e135-46c0-96c1-c825986f231a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDc2MDgsIm5iZiI6MTcxMTYwNzMwOCwicGF0aCI6Ii8xNjM3ODEzNzkvMzEzNTA4ODY0LTk2MGM3NTVjLWUxMzUtNDZjMC05NmMxLWM4MjU5ODZmMjMxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQwNjI4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWQ5YmY2NGZhODAyZWVmMmVjNWQ3ZjZlODJlZTJhNGQ5NjgwMDM0ZWFmMTRlYTQ2M2YxMDBmYmQxYjQ0YTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tm6y6kCeXKf1lrb8VxQIKAygwaJ9dz76i2ovVsR6Ud4)
> > ! Please go to settings, advanced, and click "Clear activity tab data". On mobile, it might show up as "Reset account"
> > You can then try the transaction once more, let me know how it goes
> 
> This worked for me thanks!

Worked for me too. Thanks mate.

**Comment by DefiLaunchApp** [comment]
Here is a screenshot showing that non of these options are working. 

Issue has been since 19th April and i cannot resolve it. 

No access to setting for "Advanced"
Cannot change Network in Wallet.

Using Portfolio > Bridge does not fix this when changing networks. 


Screenshot attached with all options exhausted?

 <img width="1149" alt="Screenshot 2024-04-26 at 8 08 12 am" src="https://github.com/MetaMask/metamask-extension/assets/156188208/9711a7a7-71ab-41c4-ada5-2088c82e7b03">

**Comment by iraninasab** [comment]
I just disabled the MetaMask in "mange extension" session. after enabling again, it asked me to whether confirm or reject the transaction that was confirmed previously in the network . I clicked reject and the problem solved.

**Comment by jgeek** [comment]
I have the workaround!
Go to chrome extension manager and disable the pit to toolbar and enable it again. it works!

**Comment by DefiLaunchApp** [comment]
That worked. Thanks guys

**Comment by ihorbond** [comment]
MM devs probably using all our hacks and workarounds to patch MM as we speak haha we better be getting some of that airdrop ...
