### ISSUE TITLE
[Bug]: MetaMask causing uncaught exception error if installed alongside Rabby

### ISSUE THREAD

**Issue by dzek69** [MetaMask/metamask-extension#30685]
### Describe the bug

A global promise rejection with a message `Cannot set property ethereum of #<Window> which has only a getter` is triggered whenever any page is loaded with both MetaMask and Rabby wallet installed. It seems to repeat when used on web3 enabled pages, ie. opening a connectkit modal triggers it again.

It happens on Chrome-based browsers and according to Sentry a lot of users are experiencing this on the page I'm developing, so you should be able to reproduce in no time. I did not test Firefox.

Connecting the wallet actually works fine, so I guess just a simple check on `window.ethereum` before writing to it should solve the problem. Or a try-catch, whatever you prefer.

### Expected behavior

No unhandled promises should happen

### Steps to reproduce

1. Use Chrome
2.  Install Rabby wallet
3. Install MetaMask
4. idk if that's needed, but set up MetaMask wallet (Rabby set up is for sure not needed)
6. Open any page
7. Open dev tools
8. Reload the page - you should see the uncaught promise error in the console

### Error messages or log output

```shell
inpage.js:1 Uncaught TypeError: Cannot set property ethereum of #<Window> which has only a getter
    at d (inpage.js:1:83636)
    at r.initializeProvider (inpage.js:1:83287)
    at Object.<anonymous> (inpage.js:1:1111)
    at Object.<anonymous> (inpage.js:1:5580)
    at 1.../../shared/modules/provider-injection (inpage.js:1:5593)
    at i (inpage.js:1:254)
    at e (inpage.js:1:414)
    at inpage.js:1:431
```

### Detection stage

In production (default)

### Version

12.12.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

It happens on current version 12.12.0, but it's happening for months (I'd say at least 3), so it's nothing new. I assume it was always like that, but Rabby apparently at some point started to set `ethereum` property with Object.defineProperty

**Comment by sleepytanya** [comment]
<img width="559" alt="Image" src="https://github.com/user-attachments/assets/a50426e0-069f-4b5b-9677-2d0770de67c3" />

**Comment by DanielTech21** [comment]
This issue is occurring on the latest version 12.18.2.
<img width="538" alt="Image" src="https://github.com/user-attachments/assets/7691e3df-6b58-40ef-8ecd-519439ab359e" />

**Comment by dzek69** [comment]
@DanielTech21 with 12.18.2 I'm seeing some fix:

![Image](https://github.com/user-attachments/assets/485750e5-c7f7-4e83-b5f7-c41dc4c76b2d)

It's no longer an uncaught exception for me and shows that MetaMask clearly understands what's going on.

I wonder why there is a difference in behavior with the same version.
I had: Rabby, MetaMask, Coinbase and Trust enabled at the moment of taking the screenshot

**Comment by epop-cs** [comment]
@dzek69,

Sorry for the lack of updates on your issue.
Since your last update, we've released a few more versions, and I am not seeing the error in 13.4. 
If you're willing to check again, can you please confirm the issue is now gone?

**Comment by adonesky1** [comment]
I am still seeing this issue on 13.5.0 but as @dzek69 notes in [his comment above](https://github.com/MetaMask/metamask-extension/issues/30685#issuecomment-2934413071) we know what's going on. Rabby grabs the `window.ethereum` global and then pulls up the ladder behind them and there's nothing we can do about it. Closing this issue for now.
