### ISSUE TITLE
[Bug]: When a token other than SOL is sent for the first time, it is mistakenly labeled as SOL within the Activity tab of the sender's account

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#32728]
### Describe the bug

When a token other than SOL is sent for the first time (to another account, sending to the same account results in the correct token name in the tx history), it is mistakenly labeled as SOL within the Activity tab of the sender's account. However, in the destination account, the token is correctly identified. Any subsequent transactions involving the same token are accurately reflected with the correct token name in both accounts. 

### Expected behavior

Token names are correctly idebtified and displayed within the Activity tab

### Screenshots/Recordings

https://github.com/user-attachments/assets/3e36208a-7059-4db4-b142-4a2c24813db2

### Steps to reproduce

1. Connect to Solana network
2. Send a token that hasn't been sent with the current MM instance
3. Observe Activity screen

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

12.18.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by aganglada** [comment]
I think this is due to `useSolanaBridgeTransactionMapping` https://github.com/MetaMask/metamask-extension/blob/main/ui/hooks/bridge/useSolanaBridgeTransactionMapping.ts, could you confirm @micaelae ?

**Comment by Unik0rnMaggie** [comment]
Reproduced:

Sent JMP token, but Activity Tab shows SOL:

https://github.com/user-attachments/assets/860ad0b5-dd3e-4c85-8fc6-5234bbe7651f

**Comment by ghgoodreau** [comment]
I dug into it and the issue looks like it lives in `ui/hooks/useMultichainTransactionDisplay.ts`.

When we send an SPL token to a fresh address we also pay a tiny bit of SOL to create the recipient’s associated token account. In `aggregateAmount` inside that hook, we build a map of all fungible assets in the tx, but then we just grab the first entry in that map. On these “first-send” transactions the SOL rent happens to be serialized first, so the hook hands back SOL and the Activity tab shows “-0.00x SOL” instead of the relevant token. Every subsequent transfer skips the rent step, only the token remains in the array, and the display looks fine.

So the quick fix is to stop assuming there’s only one asset and pick the token entry (or the largest amount) instead of the first one.

**Comment by ghgoodreau** [comment]
cc @aganglada ^

**Comment by ghgoodreau** [comment]
https://github.com/MetaMask/metamask-extension/pull/32777 here's a sample draft PR that quickfixes the bug - your team might want to come up with a different or more robust solution as this is probably missing edge cases etc

**Comment by aganglada** [comment]
Hey @ghgoodreau if you are taking care of the issue on the bridge side, I will reassign the issue to you

**Comment by javiergarciavera** [comment]
PR ready https://github.com/MetaMask/metamask-extension/pull/32823

**Comment by Unik0rnMaggie** [comment]
Still present on latest build from [here](https://github.com/MetaMask/metamask-extension/pull/32383#issuecomment-2876385524) 

https://github.com/user-attachments/assets/84e9c9cf-929b-455c-9343-f07e64abe362

Not present on Firefox:

https://github.com/user-attachments/assets/f61fdbe0-c9bd-4623-bcca-a38a2acf8721

**Comment by ziedbrini** [comment]
if the PR is merged and we tested with the latest build and it works, should we close this? @javiergarciavera @aganglada

**Comment by Unik0rnMaggie** [comment]
The issue is still present in the latest build from [here](https://github.com/MetaMask/metamask-extension/pull/32383#issuecomment-2877728117)

Sent [PNT token](https://solscan.io/tx/2AKnGDkFsikteYYRPjKTwinLM9TXtFCtHgsNM5nNaEieboBy9kud7PZvpXumB2A8hmbPW3m6NykNYMydimaQKm7a), but Activity showing SOL:

https://github.com/user-attachments/assets/fb67af8b-2eaf-41b0-b140-1adb702ba8ca

**Comment by sleepytanya** [comment]
@ziedbrini 
Same as @Unik0rnMaggie , build from [here](https://github.com/MetaMask/metamask-extension/pull/32383#issuecomment-2877728117), bug is present:

https://github.com/user-attachments/assets/61f2c406-eff3-4fdc-a47f-083bfe1f115f

**Comment by ziedbrini** [comment]
@sleepytanya the fix was merged after the latest build published from May 14. I would wait for a new build until retesting.

**Comment by Unik0rnMaggie** [comment]
Still present in the latest build from [here](https://github.com/MetaMask/metamask-extension/pull/32383#issuecomment-2881988089) 

https://github.com/user-attachments/assets/39e0b156-8071-4185-9211-7d69101d57b8

**Comment by javiergarciavera** [comment]
Fixed in latest build. Closing!
