### ISSUE TITLE
NewUI: Make pop-up tall enough to view Confirm/Cancel buttons

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3414]
Suggested in #3413.

May be difficult if we add more complexity to the confirmation window.

Maybe we make the mid-section scrollable, so the buttons are fixed at the footer?

**Comment by haydenadams** [comment]
Please do this! For me, I can't see the buttons, even when I scroll. I have to make the pop window larger and then scroll down for every single transaction.

![metamaskui](https://user-images.githubusercontent.com/9343483/37077841-bbad2908-21aa-11e8-83b1-8214da83627e.png)

**Comment by haydenadams** [comment]
Please do this! For me, I can't see the buttons, even when I scroll. I have to make the pop window larger and then scroll down for every single transaction.

![metamaskui](https://user-images.githubusercontent.com/9343483/37078055-a160fe5c-21ab-11e8-9f70-e41ec85c8069.png)

**Comment by haydenadams** [comment]
Please do this! For me, I can't see the buttons, even when I scroll. I have to make the pop window larger and then scroll down for every single transaction.
![metamaskui](https://user-images.githubusercontent.com/9343483/37078072-b6ccdcc0-21ab-11e8-9b0e-2281853c24ad.png)

**Comment by haydenadams** [comment]
Please do this! For me, I can't see the buttons, even when I scroll. I have to make the pop window larger and then scroll down for every single transaction.

![metamaskui](https://user-images.githubusercontent.com/9343483/37078101-df4b7c56-21ab-11e8-8546-51f71765325c.jpg)

**Comment by haydenadams** [comment]
> Maybe we make the mid-section scrollable, so the buttons are fixed at the footer?

Fixing to header or footer both sound good to me

**Comment by kumavis** [comment]
Fixed!

**Comment by haydenadams** [comment]
You sure? My MetaMask is up to date at 4.7.0 and still has this issue

**Comment by danfinlay** [comment]
@haydenadams Latest version is 4.7.3.

**Comment by danfinlay** [comment]
That said, I'm not sure this was fixed in it. @danjm may be able to answer/reopen.

**Comment by haydenadams** [comment]
@danjm @danfinlay  I just tested again in 4.7.3 and can confirm the issue remains

**Comment by danjm** [comment]
@haydenadams what browser (and browser version) are you using?

**Comment by bdresser** [comment]
@danjm i see this too, but only for token transfers - they use a different component that still shows the large round address avatars

**sending ETH**
<img width="200" alt="screen shot 2018-06-13 at 10 44 38 am" src="https://user-images.githubusercontent.com/1016190/41368502-f85196f2-6ef6-11e8-8b73-06cc15bbc6e1.png">


**token transfer**
<img width="200" alt="screen shot 2018-06-13 at 10 44 15 am" src="https://user-images.githubusercontent.com/1016190/41368500-f818f234-6ef6-11e8-8760-e7df6c99f3ea.png">


@haydenadams does that match what you've seen, or do you encounter this even when submitting a plain ETH tx?

**Comment by haydenadams** [comment]
@danjm Chrome  version 67.0.3396.87

@bdresser I get it when making trades on the automated market maker I'm building. Here's a link to the testnet (Rinkeby) demo if you want to try and reproduce the bug: https://uniswap.io/

**Comment by bdresser** [comment]
interesting, I'm on Chrome 67.0 and MM 4.7.4 and can't reproduce. tried ETH to token, token to ETH, token to token. (nice site btw 😃)

could you upgrade to 4.7.4 and try again? (head to chrome://extensions and click "update" if is hasn't auto-updated to 4.7.4)

and if you still see the error, some more detail on how to reproduce will be helpful

**Comment by haydenadams** [comment]
I'm on MM 4.7.4 now. I just tried a different transaction in a different DAPP and I get the same error.

I'm using a 15.4-inch (2880 x 1800) MacBook pro (maybe a screen resolution thing?). Chrome zoom set to 100%. Not sure what other details are helpful here.

**Comment by danfinlay** [comment]
Chrome extension zoom level is per-extension. It's pretty weird. So if you click the "full screen" button in MetaMask, and you adjust the zoom while in full-screen mode, that adjusts the size of everything in the popup, too. Is it possible you adjusted your zoom, @haydenadams? (It doesn't really look like it to me, but worth checking)

**Comment by haydenadams** [comment]
@danfinlay Sorry about the slow response. Wow you're right! I have chrome on 125% zoom by default since I have a large high res display and thats what was causing the issue. Opening MetaMask in fullscreen and zooming it out fixes the issue.

I still think this should be considered a bug though. Before fixing it was very annoying from a UX perspective, the fix was non-intuitive and the issue was a result of fairly standard chrome zoom settings. IMO the MetaMask popup should be designed to handle some level of zoom, or it should not be able to zoom at all.
