### ISSUE TITLE
[Bug]: MetaMask breaks with error when switching to custom network- MetaMask had trouble starting. This error could be intermittent, so try restarting the extension

### ISSUE THREAD

**Issue by Unik0rnMaggie** [MetaMask/metamask-extension#36673]
### Describe the bug

When adding a custom network, there are multiple requests to NFT API and MetaMask breaks with error:

`MetaMask had trouble starting. This error could be intermittent, so try restarting the extension`

[https://nft.api.cx.metamask.io/users/0x7c5dd7b02444d990c1b57c706205c8f7649aa9d2/tokens?c[…]tion=eyIxIjpudWxsLCIxMzI5IjpudWxsLCI1OTE0NCI6Ik9RPT0ifQ==](https://nft.api.cx.metamask.io/users/0x7c5dd7b02444d990c1b57c706205c8f7649aa9d2/tokens?chainIds=1&chainIds=1329&chainIds=59144&limit=50&includeTopBid=true&continuation=eyIxIjpudWxsLCIxMzI5IjpudWxsLCI1OTE0NCI6Ik9RPT0ifQ==)

On Firefox, when trying to add a custom network, there is a warning message:

`Still connecting to custom network. Update RPC` 

### Expected behavior

No error

### Screenshots/Recordings

https://github.com/user-attachments/assets/c00969cf-0be3-4ab5-87fc-2cf33b4f64a6

https://github.com/user-attachments/assets/d6de4d24-040b-42d6-8282-b87dbc7e7cb2

<img width="477" height="904" alt="Image" src="https://github.com/user-attachments/assets/b11fc1f6-d7b4-4d59-810d-dcac91f6d01d" />

<img width="753" height="907" alt="Image" src="https://github.com/user-attachments/assets/6f79b3cf-6061-4946-a71c-c3f2ee0f8a96" />

<img width="1949" height="1274" alt="Image" src="https://github.com/user-attachments/assets/4c7de435-e652-484d-b11d-40d2f9a79623" />

### Steps to reproduce

1. Add any custom network
2. Open Network manager on tab Custom networks
3. Inspect network requests

### Error messages or log output

```shell

```

### Detection stage

During release testing

### Version

13.5.0

### Build type

None

### Browser

Firefox, Chrome

### Operating system

MacOS

**Comment by juanmigdr** [comment]
Hello, this issue should be fixed now, could you please confirm? Thank you!

**Comment by Unik0rnMaggie** [comment]
The infinite loop issue is now resolved. there are no more requests to NFT API:

[https://nft.api.cx.metamask.io/users/0x7c5dd7b02444d990c1b57c706205c8f7649aa9d2/tokens?c[…]tion=eyIxIjpudWxsLCIxMzI5IjpudWxsLCI1OTE0NCI6Ik9RPT0ifQ==](https://nft.api.cx.metamask.io/users/0x7c5dd7b02444d990c1b57c706205c8f7649aa9d2/tokens?chainIds=1&chainIds=1329&chainIds=59144&limit=50&includeTopBid=true&continuation=eyIxIjpudWxsLCIxMzI5IjpudWxsLCI1OTE0NCI6Ik9RPT0ifQ==)

However, the issue with adding custom networks is still present:

```
Still connecting to custom network. Update RPC
Unable to connect to custom network
```
https://github.com/user-attachments/assets/ae6795e1-eb40-4495-94f1-407558edbe90

<img width="1966" height="1200" alt="Image" src="https://github.com/user-attachments/assets/bdbee0a3-61f5-4706-8ec3-7ee52d1e4aa1" />

**Comment by Unik0rnMaggie** [comment]
The RPC issue is still present in the latest build from [here](https://github.com/MetaMask/metamask-extension/pull/36549#issuecomment-3385548317) 

```
Still connecting to custom network. Update RPC
Unable to connect to custom network
```

https://github.com/user-attachments/assets/8dc42603-626c-4412-80a5-d77ef6709b9b

**Comment by Unik0rnMaggie** [comment]
When MetaMask is reloaded, the issue is fixed.

since there is a workaround, down grading severity to sev2:

https://github.com/user-attachments/assets/496e9882-017e-49d1-98a4-c86384d41123

**Comment by juanmigdr** [comment]
Release blocker was resolved 2 days ago [here](https://github.com/MetaMask/metamask-extension/issues/36673#issuecomment-3381369547)

The other issue has been opened as a separate ticket and Sev2 [here](https://github.com/MetaMask/metamask-extension/issues/36752)
