### ISSUE TITLE
Problem with nonce calculation causes approved transactions to not be submitted

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4086]
May be related to #3881.
Also related to #3771.

We have seen a number of users who submit transactions that get stuck in the "Approved" state, but never submit to the network.

Looking at state logs, these transactions never progress past the user approval. The next step is nonce calculation, so it is likely the bug is in nonce calculation.

We have also seen some stack overflow bugs, and it has been suggested it could be related to this.

In all of the cases of this bug I have inspected, the problem begins after one transaction fails on submit in response to a server error, like `Intrinsic gas too low` or `Nonce too low`, so we may be able to test this with a transaction pool that includes a failed transaction as its most recent one.

We should also add a nonce calculation test for when the server throws an error in response to `eth_getTransactionCount`.

**Comment by frankiebee** [comment]
update:
anything failing during or after `nonceLock = await this.nonceTracker.getNonceLock(fromAddress)` in transaction controller#approveTransaction will not properly exit the `try` and just hand

**Comment by frankiebee** [comment]
closing fixed by #4128 and #4131

**Comment by rhlsthrm** [comment]
Still having this nonce issue when connecting to a local blockchain that gets out of sync with Metamask.

**Comment by danfinlay** [comment]
@rhlsthrm Please open a new issue with detailed reproduction steps.

**Comment by rhlsthrm** [comment]
https://github.com/MetaMask/metamask-extension/issues/4361
