### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by arthurlataks** [MetaMask/metamask-extension#4431]
I see that you updated error reporting and now instead of printing whole stack trace in the error message you print actually meaningful message, that is nice. Unfortunately it seems that 'error' event is not being fired anymore, instead only the error from MetaMask extension is being printed in the console.error, so as a result, my logic in the `.on('error', ...)` is ignored.

```
web3.eth.sendTransaction(transaction)
    .on('transactionHash', resolve)
    .on('error', console.log);
```

**Comment by fradias** [comment]
Same problem here. My web3.eth.sendTransaction(transaction) catch is ignored.

**Comment by DaneWiid1** [comment]
Same issue here. Any chance we can get that error event added back in after the new console error so dapps can react to the transaction reject

**Comment by jobsamuel** [comment]
This problem is super annoying. Our dApp is broken because of this :cry:

**Comment by bitpshr** [comment]
The builds at https://github.com/MetaMask/metamask-extension/pull/4433#issuecomment-393875724 should fix this bug, feel free to test them until they're released. We plan to merge this fix and to cut a patch release today. Sorry for the issue, we're on it!

**Comment by AntonCorbijn** [comment]
can you please let me know when and where can we use the fixed version? because I just installed from chrome store and still seeing the issue.
thanks for your updates!

**Comment by wjmelements** [comment]
Until the patch is released, you can install the build from file https://github.com/MetaMask/metamask-extension/pull/4433#issuecomment-393945838
