### ISSUE TITLE
Internal JSON-RPC error is not specific enough

### ISSUE THREAD

**Issue by RobertoC27** [MetaMask/metamask-extension#4559]
Hello, i'm working with metamask and was testing a transaction that should trigger a revert statement inside my contract. When the error is thrown metamask gives the following output:
![image](https://user-images.githubusercontent.com/8262009/41312727-104e1850-6e45-11e8-96d2-2d61e06cab16.png)
this was while using Firefox with Metamask extension installed

the following is the result of using on Chrome without the metamask extension
![image](https://user-images.githubusercontent.com/8262009/41312792-4722dde8-6e45-11e8-9e50-6b3a17c5e885.png)

So as you can see i suppose the error message the extension gets its the same as the one on screenshot #2 

and here is the code that produces the throw
![image](https://user-images.githubusercontent.com/8262009/41312895-9ad8ee28-6e45-11e8-8a8f-346c09abca6c.png)

OS: Windows 10
Browser with metamask: Firefox 60.0.2 (64-bit)
Browser without metamask: Chrome Versión 67.0.3396.79 (Build oficial) (64 bits)
working with Ganache CLI v6.1.0 (ganache-core: 2.1.0) 
the command i use to launch ganache is the following `ganache-cli --noVMErrorsOnRPCResponse --port 9494 -m "main wing tag lumber seat image defy sign pair cat frost music"`

my question is, if metamask knows what error was thrown, could you propagate it to the developers since the error we get is kind of cryptic. So we could adjust our frontend for it

**Comment by tim-hub** [comment]
I got same issue

**Comment by tim-hub** [comment]
I fixed this issue in my project. The issue is from contract.

**Comment by RobertoC27** [comment]
I'm aware that this issue is caused by the contract, in my case when an unauthorized account tries to perform an action with the smart contract's data (which is expected to cause a `revert()`), but a way to catch or interact with this kind of 'expected' errors would be nice

**Comment by official-akshayjadhav** [comment]
I am also getting same issue

**Comment by jhogg11** [comment]
> I fixed this issue in my project. The issue is from contract.

How did you fix it?  I've implemented simple numbered revert codes, but I'm still wondering if there's a better solution.  Here's an example that would be used in the contract:

`require(somethingThatMustBeTrue, "1");`

And catching the error would look something like this:
```
switch(true) {
    case err.message.includes('revert 1"'): return "Something wasn't true";
    case err.message.includes('revert 2"'): return "Something else wasn't true";
    default: return "Something wasn't true, but we're not sure what"
}
```

**Comment by knuseski** [comment]
So still not fix for this ???
How can I show on screen the specific error from my contract whet in hits
require(_num > 10, "Lower than 10"); for example

**Comment by stacksideflow** [comment]
@tmashuang May I ask why this issue was closed? AFAIK rejection reason is still overwritten by "Internal RPC error" message

**Comment by stacksideflow** [comment]
@tmashuang alright, my bad. Please disregard this comment

**Comment by yves-ganza** [comment]
I'm not sure why this issue got closed but a solution I came up with was to `console.log(Object.keys(error))` which printed out  `['reason', 'code', 'error', 'method', 'transaction']` and as you can see from the keys we have an actual error object with a relevant 'message' key. Hope this helps!
