### ISSUE TITLE
NewUI: Insufficient balance not clear

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4955]
The new Confirmation screen does not show the sender's balance, and when the balance is insufficient for the tx fee, I didn't notice an obvious message of why.

We should either:
- Add balance to the UI
- Make sure "insufficient balance" is highly visible when it appears.

**Comment by alextsg** [comment]
@danfinlay Can you screenshot what you're seeing? Is the red box showing the Insufficient Balance error not appearing?

**Comment by alextsg** [comment]
This was probably due to a simulationFail, which as been fixed with #5000

**Comment by musalbas** [comment]
I think this issue is still present in the latest version of MetaMask. I tried confirming a transaction where there wasn't a sufficient Eth balance to cover the gas fee, and the confirm button wasn't clickable. In my case I was trying to send DAI, but had 0 Eth in my wallet.
