### ISSUE TITLE
Error: gas required exceeds allowance or always failing transaction at chrome-extension

### ISSUE THREAD

**Issue by ricardosardenberg** [MetaMask/metamask-extension#5048]
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? 
Error: gas required exceeds allowance or always failing transaction at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1723632 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1273654 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:369926 at o (chrome-

> Balance is 18 ether for 0x75738901541f92cefe1733427c3e7a69560c7f1d account on ROPSTEN

> Gas Limit is 3000000

> Value : 1 Ether

> http://remix.ethereum.org/#optimize=true&version=soljson-v0.4.24+commit.e67f0147.js

> Metamask 4.9.2

> Multiple simple Smart Contracts can not be deployed to ROPTSTEN even with good balance of Ether

> This used to work...it is not working with new Metamask

>

**Comment by bdresser** [comment]
@ricardosardenberg what browser are you using? and if you have a moment, could you send your state logs to support@metamask.io and reference this issue number? Instructions [here](https://consensys.zendesk.com/hc/en-us/articles/360004133432-How-to-Download-State-Logs-Old-Ui)

@danjm could you take a look?

**Comment by jennypollack** [comment]
Hey @ricardosardenberg can you share a [gist](https://gist.github.com/) of your HelloWorld.sol?

**Comment by ricardosardenberg** [comment]
contract Mortal {
    /* Define variable owner of the type address */
    address owner;

    /* This function is executed at initialization and sets the owner of the contract */
    function Mortal() { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() { if (msg.sender == owner) selfdestruct(owner); }
}

contract Greeter is Mortal {
    /* Define variable greeting of the type string */
    string greeting;

    /* This runs when the contract is executed */
    function Greeter(string _greeting) public {
        greeting = _greeting;
    }

    /* Main function */
    function greet() constant returns (string) {
        return greeting;
    }
}

**Comment by rsardenberg** [comment]
exact same problem happening in a different machine, now using FIREFOX...

very likely to be related to how METAMASK is doing gas estimation

I suggest someone looks into **eth_estimateGas**

Gas estimation failed
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
[731]</o.prototype.handleRequest/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:1723632 [549]</value/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:1273654 [114]</</</q/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:369924 o@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:388155 [114]</</</xe/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:372754 [114]</</</q/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:369924 c@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:373032 [114]</</</ke/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:373070 Ht@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432/background.js:1:382434 [114]</</</Ae/<@moz-extension://577b6e42-91cd-4dc0-81fc-5c9629e76432

**Comment by sdtsui** [comment]
We're running into the same issue helping some folks interact with their token contract.
I've included the contract address on Rinkeby, ABI, inputs, and a repro video from MyCrypto's contract interaction interface.  @alextsg @danjm feel free to ping me if I can clarify anything.

[09182018-MM-RPC-Error-Repro.zip](https://github.com/MetaMask/metamask-extension/files/2394340/09182018-MM-RPC-Error-Repro.zip)

**Comment by sdtsui** [comment]
Of note: the same flow works fine when signing with a hardware wallet (Trezor).  It's just the uncaught error from MetaMask that blocks responsiveness.  If there's a way to forward this to MyCrypto as well so less opaque errors can be added, feel free to @-me back. Thanks.

**Comment by DmitryMihaylov** [comment]
Аналогичная ошибка в Yandex Browser, Metamask 3.14.1

transact to Token.transfer errored: Error: gas required exceeds allowance or always failing transaction
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:93936:44
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72345:9
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:11758:16
    at next (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:16600:29)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12243:16
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:11758:16
    at replenish (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12278:25)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12287:9
    at eachLimit$1 (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:14467:24)
    at Object.<anonymous> (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12317:16)
    at RpcEngine._runReturnHandlersUp (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72439:13)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72357:22
    at nextTask (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:16595:14)
    at next (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:16602:9)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12243:16
    at checkForCompletion (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72376:16)
    at nextTask (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:16595:14)
    at next (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:16602:9)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12243:16
    at completeRequest (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72430:9)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12411:9
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:11758:16
    at replenish (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12278:25)
    at iterateeCallback (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12268:17)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12243:16
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:12408:13
    at end (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:72415:11)
    at chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:39417:9
    at d (chrome-extension://keoanijiealjeplfaflkcgijnnflaine/scripts/background.js:8365:26)

**Comment by bdresser** [comment]
Is anyone still having this issue with MM v6.3.0 or later?

**Comment by Tayyib-A60** [comment]
Yes I am, same error as @DmitryMihaylov

**Comment by SwJay** [comment]
Is it fixed now? I got the same error with MM v6.5.3.

**Comment by tmashuang** [comment]
Can anyone still having this issue @Tayyib-A60 @SwJay describe their reproduction steps? Also, would like to know what the gasLimit is on these transactions.

**Comment by Tayyib-A60** [comment]
I had the issue fixed by uninstalling and reinstalling a newer version of metamask

**Comment by SwJay** [comment]
> Can anyone still having this issue @Tayyib-A60 @SwJay describe their reproduction steps? Also, would like to know what the gasLimit is on these transactions.

Fixed it by indicating "gas" and "gasPrice" when provoking a contract method, though it used to work fine with elder version of web3js and metamask.

**Comment by heyJonBray** [comment]
Currently getting this same error while verifying any signature requests through Unstoppable Domains using my Ledger Nano X.

**Comment by emelendez89** [comment]
Just got this on `8.0.8 (latest)` on Brave Browser `Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit) (latest)`
I wanted to remove token from UniSwap Pool v2...
Already tried unistalling and re-installing and didn't work... all I got was an empty extra ETH wallet (I suppose it's the default to create a new wallet even tho I clicked on import)

**Comment by emelendez89** [comment]
I just find out that the issue it's actually a 0x00 on the Nonce when signing a transaction: https://github.com/Uniswap/uniswap-interface/issues/835#issuecomment-672448753

This same thread/issue has a workaround interacting directly with the contract on etherscan. Hope this helps any other lost soul wandering around.

**Comment by ihlec** [comment]
> I just find out that the issue it's actually a 0x00 on the Nonce when signing a transaction: [Uniswap/uniswap-interface#835 (comment)](https://github.com/Uniswap/uniswap-interface/issues/835#issuecomment-672448753)
> 
> This same thread/issue has a workaround interacting directly with the contract on etherscan. Hope this helps any other lost soul wandering around.

Thanks for pointing that out.
I also end up with a 0x00 nonce on the _approve signature request_.
Therefore, the _remove_ transaction nonce does not match the signature nonce and the Uniswap contract fails to permit() the transaction.

I am surprised that this issue does not affect more users.

**Comment by DreamWuGit** [comment]
I also get this error when I try to add liquidity to uniswap V2 in roposten 
inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance (8000029) or always failing transaction 

any solution to walk around ?  I tried of searching but without feasible . Thanks

**Comment by tmashuang** [comment]
Closing, I have reproduced sdtsui steps and the OP error doesn't display but a different error with the contract in execution. The error as of this comment is `execution reverted`. There are a number of reasons a contract can fail with this error, and gas estimation on our side can we one of them as well. If you have any more additional information to help debug. provide your detailed reproduction steps as well as contract addresses to help reproduce the issue.
