### ISSUE TITLE
Ledger / Trezor signing unicode messages does not callback

### ISSUE THREAD

**Issue by mjdietzx** [MetaMask/metamask-extension#5523]
When signing a message with hardware wallets (tested on both Ledger Nano S and Trezor, with both showing the same behavior):

(web3 injected into browser by MetaMask 0.2.x?)
```javascript
const message = web3.fromUtf8('Hello world!');
web3.personal.sign(message, address, (e, r) => { console.log(e, r) });
```

(web3 1.0.0)
```javascript
const signature = await this.web3js.eth.personal.sign('Hello world!', address);
```

Both have inconsistent and failing behavior. Sometimes MetaMask actually pops up with the prompt to sign the message. In this case, the signing prompt appears on the HW wallet. From here it is again inconsistent, sometimes the callback of `sign` is actually triggered and we get the signature. Other times I can tell MetaMask receives the signature (it stops loading), but the callback is never triggered.

And sometimes MetaMask never even shows the pop-up to sign the message. And there is no error message or anything. I've been very confused with this bug. Any ideas? There also seems to be some state going on (ie I have to switch between accounts in metamask.) But very hard to figure out a pattern here.

Any tricks / known issues with Hardware wallets? I know crypto kitties seems to work well with signing a message via MetaMask for their login. So I know its doable but defiently some strange behavior going on.

**Comment by mjdietzx** [comment]
<img width="1037" alt="screen shot 2018-10-15 at 1 51 12 pm" src="https://user-images.githubusercontent.com/7217256/46949354-72ca0180-d081-11e8-92e0-4b6cd7f63352.png">

This is what it looks like after i sign message (submit in metamsk and then confirm on ledger). It shows that metamask finishes loading, but the callback / no signature is received in code.

Then if i call `personal.sign` again after this, MetaMask never even shows a pop-up to confirm the sig

**Comment by tmashuang** [comment]
Unfortunately, I could not reproduce this behavior. With the snippet you provided I was able to sign both messages through both of the hardware wallets in the developer console. Trezor firmware 1.6.2 and Ledger firmware 1.0.8. Regarding the popup on two sequential signs, if the Metamask popup is open already (the notification with the title `MetaMask Notification`) it will not create another popup. But will add it to the list of messages/txs in the extension view.

**Comment by mjdietzx** [comment]
Hey @tmashuang , thanks for the reply. I actually just figured out the issue. it's because i had unicode in the message i was signing! Hot wallets in metamask work totally fine, but there seems to be a silent failure when hardware wallets try to sign unicode. So throw an emoji or chinese char in the msg your signing and you should be able to reproduce.

**Comment by tmashuang** [comment]
Hmm, its possible that Trezor/Ledger doesn't know how to handle the unicode/surrogate pairs. I don't see the emoji on my Trezor screen, just blank spaces. Will rename this issue and leave it open for now till we know more.

**Comment by alexanderatallah** [comment]
@brunobar79 @tmashuang  an easy way to reproduce this issue is to go to https://danfinlay.github.io/js-eth-personal-sign-examples/ and click `personal_sign`, with your MetaMask connected to a Ledger.

What's the status on this issue? Basically signatures are not doable with Ledger, since most DEXs use personal_sign or sign typed data, so this is probably affecting a good number of apps

**Comment by alexanderatallah** [comment]
@brunobar79 hey any updates here? been seeing an increasing number of our users run into this issue

**Comment by brunobar79** [comment]
@alexanderatallah  I haven't been able to look at this one yet and I won't until next year.

Honestly I'm not 100% sure this is a bug on our end or it's blowing up on the ledger side. 
In the meantime  you could ping Ledger and make sure their firmware supports unicode.

Also, If you want to give it a try you can fork this repo (branch gh-pages) and you'll see that message signing happens here:  https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/gh-pages/ledger-bridge.js#L99

You can test that with a local webserver, completely isolated from the MetaMask extension context.
If you give it a try and have any questions please LMK and I'll be happy to help.

**Comment by EagleTM** [comment]
I believe I'm, experiencing this using personal_sign on 0x and related DEX 
To reproduce use https://0x.org/portal/account and try "generate order" with a hw wallet (Trezor in my case). It asks to sign but fails to pass it to Trezor / pop-up Trezor confirmation. It works fine with the built-in wallet of metamask though.

Don't worry "generate order" will just output json and not actually trade.

**Comment by alexanderatallah** [comment]
@brunobar79 it's next year! Any way you could help with this now? There's an extension called SpaceSuit that seems to be working for Ledger (https://github.com/spacesuit-extension/SpaceSuit) and it's based on MetaMask's code, so the issue might be on your end after all.

In case it isn't we filed this issue for Ledger, but got no response. https://github.com/LedgerHQ/ledger-app-eth/issues/59

**Comment by brunobar79** [comment]
Fixed via https://github.com/MetaMask/eth-trezor-keyring/pull/16 (trezor)
Fixed via https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/12 (ledger)

**Comment by justinkchen** [comment]
I'm still getting issues with this I think. any other comments or updates about how to fix it?

**Comment by bdresser** [comment]
@justinkchen what MM version are you running?

**Comment by justinkchen** [comment]
7.0.1 with ledger 1.5.5, it just spins and hangs forever for me when trying to personal_sign a json string which contains no special characters

**Comment by alexanderatallah** [comment]
This issue needs to be reopened! Looks like transactions don't work either.

**Comment by heyJonBray** [comment]
Everything was working just fine until today, when transactions were sent to MetaMask (account connected to Ledger Nano X hardware wallet), no confirmation dialogue came up.

Sent a signing request which was denied. Tried to send another request, and no popup came up in the browser: "Waiting for Security Key" as per the usual.

Ethereum Contract data enabled on Ledger Nano X [Firmware v1.2.4-4]
MetaMask Version: 8.0.10
Ledger Live Version: 2.14.0
Browser: Brave Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)

Tried resetting MetaMask account, clearing browser cache, restarting computer, and disconnecting all websites from my Ledger.
Reconnected, still had the same issue.

Currently trying to remove liquidity from a yield farming at: https://www.ampleforth.org/geyser/beehiveV2-uniswap-weth-ampl
