### ISSUE TITLE
Failed gas estimation causes JSON-RPC error -32603

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/metamask-extension#7286]
**To Reproduce**

I'm not 100% sure what the precise cause of this bug is, but there exists a combination of 1) Solidity code 2) Ganache running locally 3) MetaMask v7.2.3 where a contract function invocation fails as such:

```
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: "Internal JSON-RPC error.", data: {…}, stack: "Error: "message" must be a nonempty string.↵    at…eogaeaoehlefnkodbefgpgknn/background.js:1:1207412"}
```

The fix is to specify the `gasLimit` in the code. As such, I believe that this is either a bug in Ganache's gas estimation mechanism, or the way that MetaMask makes gas estimation requests.

I hope this helps anyone who's searching for a solution. In the meantime, I'll work on a simple example to reproduce this bug.

**Comment by chipueatfast** [comment]
I got this problem too. My method is just a simple getState from the smart contract and now they threw an error, I tried to add gasLimit but clearly this method does not need any gasLimit. This happen after the MetaMask get updated.

**Comment by fullammo** [comment]
I have the same problem here with Metamask 7.3.1. Can you suggest a version where this does not cause a problem? Thanks in Advance

**Comment by daithi-coombes** [comment]
Same issue. Trying to work with `Validator Sets` on a `parity poa` client. Using remix ide so no option to set `gasLimit` in code. Metamask resets gasLimit when I try setting it to zero.

**Comment by peppeppep** [comment]
getting this error as well... the view function that triggers this error returns (uint[] memory) so maybe that's the common thread

**Comment by weijiekoh** [comment]
This issue isn't about view functions, by the way.

**Comment by jamesmorgan** [comment]
I am also seeing this issue, triggering on MM 7.3.1 in both Remix and no various . networks. Also seeing issues locally connecting to ganache when using MM atm, not sure if this is related

**Comment by benjaminaaron** [comment]
I have the same issue. Setting `gasLimit` didn't help. No problems calling that particular function via `truffle console` though.
Thanks for posting this issue @weijiekoh! Any progress on the simple example to reproduce the bug?

**Comment by waylandc** [comment]
I get same error on MetaMask 7.4.0 simply calling a balanceOf() method on a locally deployed ERC20 contract. FWIW, I can get the balanceOf() from truffle console but get this error when trying from web3+MM.

`    myERC20Contract.methods.balanceOf('0xc056617cE9b791287798BCBa0aA3E7d4c15782ea').call({ from: '0xc056617cE9b791287798BCBa0aA3E7d4c15782ea' }, function (error, balance) {
      console.log(balance);
    });
`

**Comment by crazyrabbitLTC** [comment]
I'm having the same problem, it seems in my case, when calling a public function: `myContract.methods.someMethod().call()` I needed to add the `{from: <myAddress>}` in order of it to working inside the `.call()`. 

This works: 
`myContract.methods.someMethod().call({from: <myAddress>})`  

The error message could be a bit more informative however.... :-)

**Comment by weijiekoh** [comment]
I haven't gotten around to reproducing this bug, but I suspect it has to do with a situation where contract A calls a function in contract B, and Ganache can't estimate the gas needed.

To reiterate - this is not about view functions. It has to do with send functions (which you pay gas to trigger).

**Comment by TimTinkers** [comment]
In this case we were receiving this issue due to running our test cases against an older version of our smart contract. Deleting our `build` folder and completely restarting our Ganache workspace made certain that our most up to date smart contract was actually the one being utilized.

**Comment by briangu33** [comment]
I ran into this issue as well when attempting to send transactions with `ethers.js` (some fraction of attempted transactions fail). In case anyone else is experiencing the same, using [overrides](https://docs.ethers.io/ethers.js/html/api-contract.html#overrides) to manually set the gas cost seems to fix the issue. Example:
`async move(args: MoveArgs): Promise<providers.TransactionReceipt> {
    let overrides: any = {
      gasLimit: 1000000
    };
    const tx: providers.TransactionResponse = await this.contract.move(...args, overrides);
    return tx.wait();
  }`

**Comment by yqrashawn** [comment]
In my case, the error is thrown out here
https://github.com/MetaMask/eth-json-rpc-errors/blob/226134b0a9c3aebe3c2fa1112d8ad54ef018c48f/src/classes.js#L22
The version of `eth-json-rpc-errors` is `1.1.0`.
It's called here
https://github.com/MetaMask/eth-json-rpc-middleware/blob/5bf9eb4fc7924c65636a3cb5d19648489c8aed04/fetch.js#L79
The `body.error` is a `{code: Number, message: String, .....}`.

Seems it's fixed by below commit.
https://github.com/MetaMask/eth-json-rpc-middleware/commit/212c269

**Comment by yqrashawn** [comment]
There're conflicts between `eth-json-rpc-errors@2.0.0` and `eth-json-rpc-middleware@0.4.4`.  

https://github.com/MetaMask/eth-json-rpc-errors/commit/53d76f64903032b9f22d9a6da7ce849427fc3ee5#diff-5c8b199a98cb05fcfa67ad0a331c165bR221

https://github.com/MetaMask/eth-json-rpc-middleware/commit/212c269

Which will lead to `"[object Object]"` in error message.

**Comment by shawnyang91** [comment]
Same issue calling function with gas price 0 on my private chain.
version 7.7.1

**Comment by mitdralla** [comment]
I am also having this result and can reproduce on 2 machines.

**Comment by GuillaumeCisco** [comment]
I had the issue, putting `gasLimit` to `30000` solved it.
Don't know why

**Comment by lildata** [comment]
I had the same issue, it popped out of nowhere.
Setting up the `gasLimit` did not do anything, I suspected a nonce problem since everything worked on Rinkeby. 
So resetting the account fixed it, but of course I lost all my transactions history 😓

Metamask 7.7.2
Web3.js 1.2.4
Ganache CLI v6.7.0 (ganache-core: 2.8.0)
Solc 0.5.11+commit.c082d0b4.Emscripten.clang

**Comment by xlwwww** [comment]
Setting gasLimit does not work. 
so how to fix it? What do you mean by resetting account?

**Comment by Gudahtt** [comment]
Thanks for the report!

It seems that most people were encountering this on v7 of the extension. Has anybody reproduced this recently, on the latest version of the extension?

**Comment by Ghostfly** [comment]
repoduced with metamask latest 

(MetaMask Version : 9.4.0)

**Comment by AdityaChaudhary** [comment]
Getting an error with the similar error code when trying to create a new Liquidity Pool on Uniswap.

`MetaMask - RPC Error: execution reverted: STF {code: -32603, message: "execution reverted: STF", data: {…}}`

`index.tsx:267 Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: STF",`

**Comment by mindfulme** [comment]
> Getting an error with the similar error code when trying to create a new Liquidity Pool on Uniswap.
> 
> `MetaMask - RPC Error: execution reverted: STF {code: -32603, message: "execution reverted: STF", data: {…}}`
> 
> `index.tsx:267 Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: STF",`

it seems like you are forking uniswap

**Comment by Kwame0** [comment]
I'm getting on local blockchain. truffle. calling a public function on a contract. no args needed. (Internal JSON-RPC Error)

**Comment by afanso** [comment]
> 尝试在 Uniswap 上创建新的流动性池时出现类似错误代码的错误。
> 
> `MetaMask - RPC Error: execution reverted: STF {code: -32603, message: "execution reverted: STF", data: {…}}`
> 
> `index.tsx:267 Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: STF",`

创建流动池的时候遇到了同样的问题，有解决方案吗？

**Comment by matthew2010** [comment]
It is very possible that the RPC endpoint you are using to connect to the network with MetaMask is congested or experiencing technical problems. This is still a problem, but **I found a solution that may work for you if you have the same problem**.

For Polygon you can add another RPC endpoint. 

Here is a list of RPC endpoints for Polygon and a reminder of how to set it up:
[https://docs.dfyn.network/guides/changing-polygons-rpc-endpoint-on-metamask](https://docs.dfyn.network/guides/changing-polygons-rpc-endpoint-on-metamask)

I think the answer should be the same for other chains like Arbitrum.

**Comment by keven0403** [comment]
Internal RPC Error. Try again after some time..

**Comment by martinmunillas** [comment]
this error is happening to me in version 10.8.1 of metamask, in a development ganache chain
<img width="1440" alt="Screen Shot 2022-01-02 at 22 46 08" src="https://user-images.githubusercontent.com/65319051/147894895-f9e9fb0c-0179-490d-8187-a3fb65d3b26a.png">

**Comment by StefanKnezevic1** [comment]
I had the same error (JSON-RPC error -32603). My issue was the I defined my payable in my smart contract like this:
"function deposit() payable public{}", whereas I needed to make use of the fallback() and receive() functions. I replaced that line of code with "fallback() external payable{}" and "receive() external payable()" and it works!

**Comment by binsta** [comment]
I had same one `` RPC Error: execution reverted: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted","data":{"originalError":{"code":3,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000032","message":"execution reverted"}}}, method="call", transaction={..}}``

MetaMask 10.8.1
solidity ^0.8.4;

**Comment by baselka** [comment]
I'm encountering it as well I'm using a private openethereum poa parity :

MetaMask 10.8.1
solidity ^0.8.4;

**Comment by skarelin** [comment]
Just got the same issue as you, guys.
Metamask warning: "This transaction is expected to fail...";
console.log() with response from application: "RPC Error: execution reverted: STF {code: -32603, ..."

In my case, solution was very easy: "`truffle migrate --reset`". Probably I used an old copy of contract.

**Comment by CrmKanashii** [comment]
Hi everyone,

I am not a programmer but I don't know where else to go regarding my issue. This thread appeared when I ran a google search and I was hoping someone here could help me.

It seems that I cannot conduct any transactions through Metamask on the polygon chain. (all other chains work fine) When I attempt to make a transaction on polygon it gives me this error.  "replacement fee too low" and then a bunch of gibberish (to me).  

I have tried changing the all of the gas parameters and I've also reset the account but no luck.  Something to note, metmask also doesn't allow me to sends tokens between accounts. (which I find very strange and makes me think this is a MM issue) 

I need access to this account as it holds my primary funds.  Any help would be greatly appreciated.

**Comment by nedgar** [comment]
@CrmKanashii It's likely trying to reuse the nonce (count of submitted transactions), so it thinks you're trying to replace an existing transaction rather than start a new one. Check the nonce # on the last several transactions. Try cancelling your earliest failed transaction in Metamask, bumping its gas price up once or twice if needed ("go faster"). If that doesn't work, in advanced settings there's a switch for letting you specify the nonce # directly.

**Comment by NekfarBaqir** [comment]
Hey guys!
[I have integrated 0x swap sdk v4 into my app ](https://docs.swapsdk.xyz/readme/managing-orders)

and this above problem happened with polygon chain when I was trying the **fillSignedOrder** function.
Here is the picture of the error:

`{
    "code": -32603,
    "message": "Internal JSON-RPC error.",
    "data": {
        "code": -32000,
        "message": "execution reverted"
    },
    "stack": "{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": -32000,\n    \"message\": \"execution reverted\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412"
}`

appreciate it in advance 🙏🙏🙏

**Comment by jinsley8** [comment]
> I have integrated 0x swap sdk v4 into my app

I have the same issue did you figure it out?

**Comment by aliawais0007** [comment]
Did anyone figure it out? I am facing the same issue due to gas fee estimation error.

**Comment by thibauld** [comment]
Not sure if it comes from "gas estimation" as the initial author suggests but "same issue here".
Using Metamask 10.23.2 on Optimism network.

Trying to swap tokens on Uniswap (on Optimism network), when clicking "Confirm Swap" button, it won't even show the metamask extension but simply produce those 2 errors:
![image](https://user-images.githubusercontent.com/197119/209878006-5e82719d-d035-426c-932c-e9ac8adbd0e5.png)
with details:
![image](https://user-images.githubusercontent.com/197119/209878359-1aaef1f2-9b4c-41c6-be0b-7fd877b44f34.png)

As it seems tied to gas estimation, I tried enabling "enhanced gas fee UI". No change. Same error.
![image](https://user-images.githubusercontent.com/197119/209878836-73536f2e-966b-431c-9929-457b941411fb.png)

I tried enabling advanced gas controls. No change. Same error.
![image](https://user-images.githubusercontent.com/197119/209878995-5f61dd81-060e-4086-a81e-778bc621d732.png)

I tried changing RPC Endpoint and used a paid RPC endpoint provided by Alchemy. No change. Same error.

It seems like a basic use case (swapping tokens on Uniswap) so I am puzzled as to where this error could come from :thinking:

**Comment by thibauld** [comment]
UPDATE on my previous comment: I solved it by swapping "less" tokens than I initially wanted. 
So, TL;DR: "Execution reverted: STF". STF means `SafeTransferFrom`. That's the name of the function that fails. It fails because either `approve()` hasn't been called or it has been called with a value inferior to the one you're trying to transfer (my case). So, in my case, it seems that somehow Uniswap called `approve()` with a weird value... which caused the follow-up swap transaction to be rejected. Hope this helps other people trying to figure this out!

**Comment by YakovL** [comment]
Got this issue yesterday (a colleague has confirmed that they had it, too); today it was gone. Metamask 10.34.1, Polygon mainnet (Withdraw tx on market.iq.space)

**Comment by harissatti** [comment]
same issue while deploying my smart contract through node  js .in first week deploying contract is working.but now it giving error.we did'nt make any changes in code.contract deploying  of 721 is working but 1155 is not . error is 

VM29:1 MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: 'Internal JSON-RPC error.', data: {…}}
code
: 
-32603
data
: 
{code: -32000, message: 'execution reverted', cause: null}
message
: 
"Internal JSON-RPC error."
[[Prototype]]
: 
Object



![Capture](https://github.com/MetaMask/metamask-extension/assets/58341295/fa8da6e5-5486-488a-927c-6c66938994a7)

**Comment by harissatti** [comment]
issue solved by just updating bytecode and abi

**Comment by sanjaybora04** [comment]
I tried everything and didnt solve the error
then i tried testing the function which was causing this error with truffle and i found out that it was throwing an warning because of a validation check, i removed the validation and it started working

**Comment by XuJieJJ** [comment]
Try to downgrade the solcjs version may solve the issue
