### ISSUE TITLE
cannot use ledger with uniswap

### ISSUE THREAD

**Issue by thedavidmeister** [MetaMask/metamask-extension#8157]
**Describe the bug**

as of this morning i tried to use ledger with uniswap and metamask on linux chrome + firefox and mac chrome across 3 different computers

clicking "confirm" never shows the approval prompt on the ledger

i am still able to use my ledger with other services that interact with the ledger directly e.g. MEW and 1inch.exchange

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to uniswap
2. try to trade or add liquidity to pool
3. click "confirm" with a ledger address attached to metamask

**Expected behavior**
A clear description of what you expected to happen.

need to see an approval prompt on ledger so i can confirm interactions with uniswap

**Screenshots**

**Browser details (please complete the following information):**
 - OS: linux + mac
- ledger nano s: latest firmware + ethereum app
- browser: chrome + firefox

**Additional context (Error Messages, etc.)**

i didn't see any error messages, the prompt simply never displayed

**Comment by tobutridaz** [comment]
I think this applies to all dapps. I am also no longer getting ledger prompts when trying to interact with it through meta-mask. Windows (Chrome/Brave). Ledger works with direct non Metamask integration.

**Comment by john-light** [comment]
Also having trouble with Ledger, for me I cannot even get MetaMask to recognize the Ledger when attempting to add an account:

![ledger-mask](https://user-images.githubusercontent.com/9424721/75794748-3adb6100-5d3f-11ea-830c-28e7c2d0dd13.png)

I tried using Ledger with Frame (frame.sh) and it works so it seems to be a MetaMask specific issue.

**Comment by Clearwood** [comment]
I am experiencing the same problem with Metamask version 7.7.5

**Comment by tmashuang** [comment]
The issue was DNS configuration related, so it may take a little while for the changes to reach all users. Seriously sorry for the inconvenience, everyone!

**Comment by lamart1** [comment]
I have same problem, but when I use Ledger directly in MyCrypto, Kyberswap, Ledger Live it is working.

**Comment by Clearwood** [comment]
It is still unsolved for me, I also can not record any kind of network activity when trying to connect the ledger

**Comment by kumavis** [comment]
The underlying issue has been resolved, however there seems to be an incorrect redirect that has been cached in some users browsers. This problem should disappear on its own when the cache expires, or you can manually clear it yourself.

please let us know if clearing the cache solved your issue or not

chrome:
![image](https://user-images.githubusercontent.com/1474978/75890527-78d4a400-5e69-11ea-99bb-2723446cdaee.png)


firefox:
![image](https://user-images.githubusercontent.com/1474978/75890393-4460e800-5e69-11ea-8ffe-ed3d019badb5.png)

**Comment by dpazdan** [comment]
Created a support article for this https://metamask.zendesk.com/hc/en-us/articles/360040084492-How-to-clear-your-browser-s-cache

**Comment by lamart1** [comment]
> The underlying issue has been resolved, however there seems to be an incorrect redirect that has been cached in some users browsers. This problem should disappear on its own when the cache expires, or you can manually clear it yourself.
> 
> please let us know if clearing the cache solved your issue or not
> 
> chrome:
> ![image](https://user-images.githubusercontent.com/1474978/75890527-78d4a400-5e69-11ea-99bb-2723446cdaee.png)
> 
> firefox:
> ![image](https://user-images.githubusercontent.com/1474978/75890393-4460e800-5e69-11ea-8ffe-ed3d019badb5.png)

For me this is working now for Brave, Firefox, Chrome

**Comment by danfinlay** [comment]
This was a problem with a fix to another Ledger bug that we released.

We've fixed this issue in version 7.7.7 as of yesterday, which all clients should auto-update to now.

If your client is not auto-updating, you can manually install the build from this page:
https://github.com/MetaMask/metamask-extension/releases/tag/v7.7.7

Using these instructions:
https://metamask.zendesk.com/hc/en-us/articles/360015489471-How-to-Install-MetaMask-Manually

**Comment by thedavidmeister** [comment]
it's working for me now thanks

**Comment by Conviley** [comment]
It still doesn't work for me! I have metamask v7.7.8  I got a Ledger nano X yesterday and i can't interact with any dapps through metamask even though i was able to connect the wallet to my metamask.  I'm on windows tested with both chrome and brave and when i confirm on metamask it doesn't prompt my ledger device. I am however able to send through metamask from my ledger

**Comment by Tbduc** [comment]
Hi,
I have encountered the same issue and clearing the cache doesn't work. Should I remove my Ledger and connect it again to Metamask? I am quite new with this feature, so I have never experienced this feature working.

**Comment by danfinlay** [comment]
Please visit support.metamask.io for support. We have articles and a form for getting individual help.

**Comment by Conviley** [comment]
@Tbduc Make sure you are allowing `contract data in transactions` on the Ethereum app on your ledger!

To enable contract data in transactions, perform the following steps:

1. Start the Ethereum app on you ledger
2. Navigate to `settings`
3. Navigate to the `Contract Data` tab
4. Enable it by pressing down both buttons 
5. Exit `settings`

Now you should be able to interact with any DApp using your ledger through metamask!

**Comment by NacionCrypto** [comment]
Hello, I am having the same problem and nothing seems to help.  I cleared the cache, reseted the metamask but still doesnt work.  It is scary because I provided liquidity to uniswap and now I can't acces to it. I see it  but can do any transaction in my metamask 🥴🥴

thanks for the help.

**Comment by joesixpack** [comment]
Still occuring in 8.0.10.  Issue needs to be re-opened.

**Comment by tmsail** [comment]
using metamask, uniswap, ledger nano s. Everything works on my metamask account 1 but nothing works on my metamask ledger
account.

**Comment by tmsail** [comment]
I am going to try Conviley's enable contract data and see if that works.

**Comment by tmsail** [comment]
well i cleared the cache in ledger live by doing the following:
1. click on settings
2. click on help
3. click on "clear cache" button

it worked! i can now sign transactions

**Comment by lawrencerook** [comment]
Hi everyone.
To enable the use of Nano Ledger on Uniswap you need to enable 'Contract data' on the Ethereum app Settings on the ledger. Once this is turned on from the device you will be able to make transactions on Uniswap.
Thanks
